[2022-02-17T03:00:00.017] [INFO] ma-core - Running Sync Shift 2PM UTC
[2022-02-17T03:00:07.931] [INFO] ma-core - add new shifts success /api/shift/sync PATCH ::ffff:127.0.0.1
[2022-02-17T03:00:07.943] [INFO] ma-core - sync shift success /api/shift/sync PATCH ::ffff:127.0.0.1
[2022-02-17T03:00:08.008] [INFO] ma-core - {"message":"Shift sync success"}
[2022-02-17T03:00:08.052] [INFO] ma-core - Shift Unassigned reminder cron launched
[2022-02-17T03:00:08.056] [INFO] ma-core - Shift Unassigned reminder cron launched
[2022-02-17T03:00:08.068] [INFO] ma-core - Shift Unassigned reminder cron launched
[2022-02-17T03:00:08.084] [INFO] ma-core - Shift Unassigned reminder cron launched
[2022-02-17T03:00:08.087] [INFO] ma-core - Shift Unassigned reminder cron launched
[2022-02-17T03:00:08.092] [INFO] ma-core - Shift Unassigned reminder cron launched
[2022-02-17T03:00:08.094] [INFO] ma-core - Shift Unassigned reminder cron launched
[2022-02-17T03:00:08.095] [INFO] ma-core - Shift Unassigned reminder cron launched
[2022-02-17T03:00:08.097] [INFO] ma-core - Shift Unassigned reminder cron launched
[2022-02-17T03:00:08.099] [INFO] ma-core - Shift Unassigned reminder cron launched
[2022-02-17T03:00:08.101] [INFO] ma-core - Shift Unassigned reminder cron launched
[2022-02-17T03:00:08.103] [INFO] ma-core - cron shift unassigned : startdate before now
[2022-02-17T03:00:08.109] [INFO] ma-core - Shift Unassigned reminder cron launched
[2022-02-17T03:00:08.111] [INFO] ma-core - Shift Unassigned reminder cron launched
[2022-02-17T03:00:08.112] [INFO] ma-core - Shift Unassigned reminder cron launched
[2022-02-17T03:00:08.114] [INFO] ma-core - Shift Unassigned reminder cron launched
[2022-02-17T03:00:08.117] [INFO] ma-core - Shift Unassigned reminder cron launched
[2022-02-17T16:10:51.169] [INFO] ma-core - database URI mongodb://localhost:27017/core
[2022-02-17T16:10:52.112] [INFO] ma-core - server started at port 5000
[2022-02-17T16:10:52.136] [INFO] ma-core - mongodb conected
[2022-02-17T16:10:52.216] [INFO] ma-core - add Client success testing testing testing
[2022-02-17T16:10:52.218] [ERROR] ma-core - add Client :missing property testing testing testing
[2022-02-17T16:10:52.219] [ERROR] ma-core - add Client :missing property NaN post 1234
[2022-02-17T16:10:52.230] [ERROR] ma-core - Delete Error : Error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/client/delete/deleteClient.service.test.js:62:33)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-17T16:10:52.231] [ERROR] ma-core - Delete Error : Error: random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/client/delete/deleteClient.service.test.js:72:33)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-17T16:10:52.259] [ERROR] ma-core - Get by System Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/client/getClientsBySystemId/getAllClientBySystemServiceTest.js:58:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-17T16:10:52.266] [ERROR] ma-core - Error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/client/update/updateClient.service.test.js:70:33)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-17T16:10:52.332] [INFO] ma-core - get all Customer success testing testing testing
[2022-02-17T16:10:52.334] [INFO] ma-core - get all Customer success NaN post 1234
[2022-02-17T16:10:52.335] [INFO] ma-core - get all Customer success testing testing testing
[2022-02-17T16:10:52.337] [INFO] ma-core - get all Customer error testing testing testing
[2022-02-17T16:10:52.338] [INFO] ma-core - get all Customer error NaN post 1234
[2022-02-17T16:10:52.347] [INFO] ma-core - get Customer success testing testing testing
[2022-02-17T16:10:52.348] [INFO] ma-core - get Customer error testing testing testing
[2022-02-17T16:10:52.356] [ERROR] ma-core - Error: random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/customer/getById/getByIdCustomer.service.test.js:88:24)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-17T16:10:52.369] [INFO] ma-core - add customer success testing testing testing
[2022-02-17T16:10:52.370] [ERROR] ma-core - add customer fail :missing property testing testing testing
[2022-02-17T16:10:52.471] [ERROR] ma-core - Delete Error : Error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/host/delete/deleteHost.service.test.js:72:33)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-17T16:10:52.478] [ERROR] ma-core - Get by System Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/host/getAllBySystem/getAllBySystemServiceTest.js:59:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-17T16:10:52.485] [ERROR] ma-core - Get by ID Error : Error: random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/host/getById/getByIdHost.service.test.js:58:24)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-17T16:10:52.490] [ERROR] ma-core - expected findOneAndUpdate to have been called exactly once, but it was called 0 times
[2022-02-17T16:10:52.499] [ERROR] ma-core - Update Error : Error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/host/update/updateHost.service.test.js:79:33)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-17T16:10:50.456] [INFO] ma-core - cancel itOperation success testing testing testing
[2022-02-17T16:10:50.456] [ERROR] ma-core - cancel ItOperation :itOperation not found testing testing testing
[2022-02-17T16:10:50.458] [INFO] ma-core - finish itOperation success testing testing testing
[2022-02-17T16:10:50.458] [ERROR] ma-core - finish ItOperation :itOperation not found testing testing testing
[2022-02-17T16:10:52.511] [INFO] ma-core - get All Active itOperation success testing testing testing
[2022-02-17T16:10:52.512] [ERROR] ma-core - get All Active ItOperation :undefined testing testing testing
[2022-02-17T16:10:52.518] [INFO] ma-core - get All Archived itOperation success testing testing testing
[2022-02-17T16:10:52.524] [ERROR] ma-core - Error occur while Getting ItOperation By System Id : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/itOperation/getAllBySystem/getAllBySystemServiceTest.js:50:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-17T16:10:52.532] [INFO] ma-core - add ItOperation success testing testing testing
[2022-02-17T16:10:52.534] [ERROR] ma-core - add ItOperation fail :missing property testing testing testing
[2022-02-17T16:10:50.471] [INFO] ma-core - remind itOperation success testing testing testing
[2022-02-17T16:10:50.471] [ERROR] ma-core - remind ItOperation :itOperation not found testing testing testing
[2022-02-17T16:10:50.473] [INFO] ma-core - send changes itOperation success testing testing testing
[2022-02-17T16:10:50.473] [ERROR] ma-core - send changes ItOperation :itOperation not found testing testing testing
[2022-02-17T16:10:52.549] [INFO] ma-core - update itOperation success testing testing testing
[2022-02-17T16:10:52.550] [ERROR] ma-core - update ItOperation :itOperation not found testing testing testing
[2022-02-17T16:10:52.578] [INFO] ma-core - delete licence success testing testing testing
[2022-02-17T16:10:52.579] [INFO] ma-core - delete licence success NaN post 1234
[2022-02-17T16:10:52.581] [ERROR] ma-core - delete Licence :licence not found testing testing testing
[2022-02-17T16:10:52.584] [ERROR] ma-core - delete Licence :licence not found NaN post 1234
[2022-02-17T16:10:52.590] [INFO] ma-core - get latest customer licence By Id success testing testing testing
[2022-02-17T16:10:52.591] [INFO] ma-core - get latest customer licence By Id success NaN post 1234
[2022-02-17T16:10:52.593] [ERROR] ma-core - get licence By Id :Missing Customer ID NaN post 1234
[2022-02-17T16:10:52.594] [ERROR] ma-core - get licence By Id :Missing Customer ID testing testing testing
[2022-02-17T16:10:52.596] [ERROR] ma-core - get licence By Id :licence not found testing testing testing
[2022-02-17T16:10:52.597] [ERROR] ma-core - get licence By Id :licence not found NaN post 1234
[2022-02-17T16:10:52.600] [ERROR] ma-core - Error occur while Getting Licence By Customer Id : Error: random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/licence/getActiveLicence/getActiveLIcenceServiceTest.js:52:17)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-17T16:10:52.604] [ERROR] ma-core - Error occur while Getting Licence By Customer Id : Error: random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/licence/getByCustomer/getByCustomerLicence.service.test.js:61:17)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-17T16:10:52.607] [INFO] ma-core - get licence By Id success testing testing testing
[2022-02-17T16:10:52.608] [INFO] ma-core - get licence By Id success NaN post 1234
[2022-02-17T16:10:52.609] [ERROR] ma-core - get licence By Id :licence not found testing testing testing
[2022-02-17T16:10:52.611] [ERROR] ma-core - get licence By Id :licence not found NaN post 1234
[2022-02-17T16:10:52.618] [INFO] ma-core - add Licence success testing testing testing
[2022-02-17T16:10:52.619] [INFO] ma-core - add Licence success NaN post 1234
[2022-02-17T16:10:52.620] [ERROR] ma-core - add Licence :missing property testing testing testing
[2022-02-17T16:10:52.622] [ERROR] ma-core - add Licence :missing property NaN post 1234
[2022-02-17T16:10:52.629] [INFO] ma-core - update licence By Customer success testing testing testing
[2022-02-17T16:10:52.631] [INFO] ma-core - update licence By Customer success NaN post 1234
[2022-02-17T16:10:52.632] [ERROR] ma-core - update licence By Customer :licence not found testing testing testing
[2022-02-17T16:10:52.634] [ERROR] ma-core - update licence By Customer :licence not found NaN post 1234
[2022-02-17T16:10:52.652] [ERROR] ma-core - delete Map By Id :MAP not found testing testing testing
[2022-02-17T16:10:52.655] [ERROR] ma-core - delete Map By Id :missing ID testing testing testing
[2022-02-17T16:10:52.656] [ERROR] ma-core - delete Map By Id :missing ID testing testing testing
[2022-02-17T16:10:52.658] [ERROR] ma-core - delete Map By Id :missing ID NaN post 1234
[2022-02-17T16:10:52.674] [ERROR] ma-core - Get by System Error : TypeError: moment(...).tz(...).format is not a function
    at /home/azer/avaxia-monitpring-app/core-service/services/map/getBySystemId.js:2:1950
    at Array.map (<anonymous>)
    at module.exports (/home/azer/avaxia-monitpring-app/core-service/services/map/getBySystemId.js:2:1771)
    at async Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/map/getAllBySystem/getAllBySystemServiceTest.js:71:17)
[2022-02-17T16:10:52.677] [ERROR] ma-core - Get by System Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/map/getAllBySystem/getAllBySystemServiceTest.js:98:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-17T16:10:52.701] [INFO] ma-core - delete module success testing testing testing
[2022-02-17T16:10:52.702] [INFO] ma-core - delete module success NaN post 1234
[2022-02-17T16:10:52.703] [ERROR] ma-core - delete Module :module not found testing testing testing
[2022-02-17T16:10:52.704] [ERROR] ma-core - delete Module :module not found NaN post 1234
[2022-02-17T16:10:52.707] [ERROR] ma-core - delete Module :missing ID testing testing testing
[2022-02-17T16:10:52.708] [ERROR] ma-core - delete Module :missing ID testing testing testing
[2022-02-17T16:10:52.713] [INFO] ma-core - get All Basic Module success testing testing testing
[2022-02-17T16:10:52.714] [INFO] ma-core - get All Basic Module success NaN post 1234
[2022-02-17T16:10:52.716] [ERROR] ma-core - get All Basic Module :missing property testing testing testing
[2022-02-17T16:10:52.717] [ERROR] ma-core - get All Basic Module :missing property NaN post 1234
[2022-02-17T16:10:52.719] [INFO] ma-core - get All Module success testing testing testing
[2022-02-17T16:10:52.720] [INFO] ma-core - get All Module success NaN post 1234
[2022-02-17T16:10:52.722] [ERROR] ma-core - get All Module :missing property testing testing testing
[2022-02-17T16:10:52.724] [ERROR] ma-core - get All Module :missing property NaN post 1234
[2022-02-17T16:10:52.729] [INFO] ma-core - get module By Id success testing testing testing
[2022-02-17T16:10:52.730] [INFO] ma-core - get module By Id success NaN post 1234
[2022-02-17T16:10:52.732] [ERROR] ma-core - get module By Id :module not found testing testing testing
[2022-02-17T16:10:52.733] [ERROR] ma-core - get module By Id :module not found testing testing testing
[2022-02-17T16:10:52.735] [ERROR] ma-core - get module By Id :module not found NaN post 1234
[2022-02-17T16:10:52.750] [INFO] ma-core - add Module success testing testing testing
[2022-02-17T16:10:52.754] [INFO] ma-core - add Module success NaN post 1234
[2022-02-17T16:10:52.757] [ERROR] ma-core - add Module :missing property testing testing testing
[2022-02-17T16:10:52.760] [ERROR] ma-core - add Module :missing property NaN post 1234
[2022-02-17T16:10:52.773] [INFO] ma-core - update module By Customer success testing testing testing
[2022-02-17T16:10:52.774] [INFO] ma-core - update module By Customer success NaN post 1234
[2022-02-17T16:10:52.775] [ERROR] ma-core - update module By Customer :module not found testing testing testing
[2022-02-17T16:10:52.777] [ERROR] ma-core - update module By Customer :module not found testing testing testing
[2022-02-17T16:10:52.779] [ERROR] ma-core - update module By Customer :module not found NaN post 1234
[2022-02-17T16:10:52.847] [INFO] ma-core - get All nomenclature success testing testing testing
[2022-02-17T16:10:52.848] [INFO] ma-core - get All nomenclature success testing testing testing
[2022-02-17T16:10:52.850] [INFO] ma-core - get All nomenclature success testing testing testing
[2022-02-17T16:10:52.851] [INFO] ma-core - get All nomenclature success NaN post 1234
[2022-02-17T16:10:52.853] [ERROR] ma-core - get All nomenclature :get All nomenclature : testing testing testing
[2022-02-17T16:10:52.855] [ERROR] ma-core - get All nomenclature :get All nomenclature : NaN post 1234
[2022-02-17T16:10:52.879] [INFO] ma-core - delete Result Form success testing testing testing
[2022-02-17T16:10:52.880] [INFO] ma-core - delete Result Form success NaN post 1234
[2022-02-17T16:10:52.882] [ERROR] ma-core - delete Result Form :task not found testing testing testing
[2022-02-17T16:10:52.883] [ERROR] ma-core - delete Result Form :task not found NaN post 1234
[2022-02-17T16:10:52.893] [INFO] ma-core - get all result form success testing testing testing
[2022-02-17T16:10:52.895] [INFO] ma-core - get all result form success testing testing testing
[2022-02-17T16:10:52.897] [INFO] ma-core - get all result form success NaN post 1234
[2022-02-17T16:10:52.899] [ERROR] ma-core - get All result form :missing property testing testing testing
[2022-02-17T16:10:52.901] [ERROR] ma-core - get All result form :missing property NaN post 1234
[2022-02-17T16:10:52.905] [INFO] ma-core - get by id Result Form testing testing testing
[2022-02-17T16:10:52.906] [INFO] ma-core - get by id Result Form NaN post 1234
[2022-02-17T16:10:52.908] [ERROR] ma-core - get by id Result Form :task not found testing testing testing
[2022-02-17T16:10:52.909] [ERROR] ma-core - get by id Result Form :task not found NaN post 1234
[2022-02-17T16:10:52.914] [INFO] ma-core - get Monitoring Activities Without Result Form success testing testing testing
[2022-02-17T16:10:52.916] [INFO] ma-core - get Monitoring Activities Without Result Form success NaN post 1234
[2022-02-17T16:10:52.917] [ERROR] ma-core - get Monitoring Activities Without Result Forms :error testing testing testing
[2022-02-17T16:10:52.919] [ERROR] ma-core - get Monitoring Activities Without Result Forms :not found error testing testing testing
[2022-02-17T16:10:52.920] [ERROR] ma-core - get Monitoring Activities Without Result Forms :error NaN post 1234
[2022-02-17T16:10:52.924] [INFO] ma-core - add result form success testing testing testing
[2022-02-17T16:10:52.926] [INFO] ma-core - add result form success NaN post 1234
[2022-02-17T16:10:52.927] [ERROR] ma-core - add result form :missing property testing testing testing
[2022-02-17T16:10:52.928] [ERROR] ma-core - add result form :missing property NaN post 1234
[2022-02-17T16:10:52.932] [INFO] ma-core - update Result Form success testing testing testing
[2022-02-17T16:10:52.933] [INFO] ma-core - update Result Form success NaN post 1234
[2022-02-17T16:10:52.935] [ERROR] ma-core - update Result Form  :task not found testing testing testing
[2022-02-17T16:10:52.936] [ERROR] ma-core - update Result Form  :task not found NaN post 1234
[2022-02-17T16:10:52.941] [INFO] ma-core - delete Role success testing testing testing
[2022-02-17T16:10:52.943] [INFO] ma-core - delete Role success NaN post 1234
[2022-02-17T16:10:52.944] [ERROR] ma-core - delete Role :role not found testing testing testing
[2022-02-17T16:10:52.946] [ERROR] ma-core - delete Role :role not found NaN post 1234
[2022-02-17T16:10:52.947] [ERROR] ma-core - delete Role :missing ID testing testing testing
[2022-02-17T16:10:52.948] [ERROR] ma-core - delete Role :missing ID testing testing testing
[2022-02-17T16:10:52.958] [INFO] ma-core - get All Role success testing testing testing
[2022-02-17T16:10:52.959] [INFO] ma-core - get All Role success NaN post 1234
[2022-02-17T16:10:52.960] [ERROR] ma-core - get All Role :missing property testing testing testing
[2022-02-17T16:10:52.963] [ERROR] ma-core - get All Role :missing property NaN post 1234
[2022-02-17T16:10:52.966] [INFO] ma-core - get by id Role success testing testing testing
[2022-02-17T16:10:52.967] [INFO] ma-core - get by id Role success NaN post 1234
[2022-02-17T16:10:52.968] [ERROR] ma-core - get by id Role :role not found testing testing testing
[2022-02-17T16:10:52.970] [ERROR] ma-core - get by id Role :role not found testing testing testing
[2022-02-17T16:10:52.972] [ERROR] ma-core - get by id Role :role not found NaN post 1234
[2022-02-17T16:10:52.980] [INFO] ma-core - get by user Role success testing testing testing
[2022-02-17T16:10:52.981] [INFO] ma-core - get by user Role success NaN get 1234
[2022-02-17T16:10:52.983] [ERROR] ma-core - get by user Role :user not found testing testing testing
[2022-02-17T16:10:52.984] [ERROR] ma-core - get by user Role :role not found testing testing testing
[2022-02-17T16:10:52.986] [ERROR] ma-core - get by user Role :role not found NaN get 1234
[2022-02-17T16:10:52.988] [INFO] ma-core - add Role success testing testing testing
[2022-02-17T16:10:52.989] [ERROR] ma-core - add Role :missing property testing testing testing
[2022-02-17T16:10:52.990] [INFO] ma-core - add Role success NaN post 1234
[2022-02-17T16:10:52.992] [ERROR] ma-core - add Role :missing property NaN post 1234
[2022-02-17T16:10:53.000] [INFO] ma-core - update Role success testing testing testing
[2022-02-17T16:10:53.002] [INFO] ma-core - update Role success NaN post 1234
[2022-02-17T16:10:53.003] [ERROR] ma-core - update Role :role not found testing testing testing
[2022-02-17T16:10:53.004] [ERROR] ma-core - update Role :role not found testing testing testing
[2022-02-17T16:10:53.006] [ERROR] ma-core - update Role :role not found NaN post 1234
[2022-02-17T16:10:53.012] [INFO] ma-core - add Role History success testing testing testing
[2022-02-17T16:10:53.014] [INFO] ma-core - add Role History success NaN post 1234
[2022-02-17T16:10:53.015] [ERROR] ma-core - add Client :missing property testing testing testing
[2022-02-17T16:10:53.016] [ERROR] ma-core - add Client :missing property NaN post 1234
[2022-02-17T16:10:53.045] [ERROR] ma-core - 
[2022-02-17T16:10:53.061] [INFO] ma-core - Get all shifts success testing testing testing
[2022-02-17T16:10:53.078] [INFO] ma-core - Get all members success testing testing testing
[2022-02-17T16:10:53.124] [INFO] ma-core - delete sla success testing testing testing
[2022-02-17T16:10:53.125] [INFO] ma-core - delete sla success NaN post 1234
[2022-02-17T16:10:53.127] [ERROR] ma-core - delete Sla :sla not found testing testing testing
[2022-02-17T16:10:53.128] [ERROR] ma-core - delete Sla :sla not found testing testing testing
[2022-02-17T16:10:53.130] [ERROR] ma-core - delete Sla :sla not found NaN post 1234
[2022-02-17T16:10:53.137] [INFO] ma-core - get sla By Id success testing testing testing
[2022-02-17T16:10:53.139] [INFO] ma-core - get sla By Id success NaN post 1234
[2022-02-17T16:10:53.140] [ERROR] ma-core - get sla By Id :sla not found testing testing testing
[2022-02-17T16:10:53.142] [ERROR] ma-core - get sla By Id :sla not found testing testing testing
[2022-02-17T16:10:53.143] [ERROR] ma-core - get sla By Id :sla not found NaN post 1234
[2022-02-17T16:10:53.150] [ERROR] ma-core - Error occur while Getting Sla By slaContract Id : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/sla/getByslaContract/getslaBySlaContract.service.test.js:70:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-17T16:10:53.160] [INFO] ma-core - add Sla success testing testing testing
[2022-02-17T16:10:53.161] [INFO] ma-core - add Sla success NaN post 1234
[2022-02-17T16:10:53.162] [ERROR] ma-core - add Sla :missing property testing testing testing
[2022-02-17T16:10:53.165] [ERROR] ma-core - add Sla :missing property NaN post 1234
[2022-02-17T16:10:53.181] [INFO] ma-core - update sla By SlaContract success testing testing testing
[2022-02-17T16:10:53.182] [INFO] ma-core - update sla By SlaContract success NaN post 1234
[2022-02-17T16:10:53.184] [ERROR] ma-core - update sla By SlaContract :sla not found testing testing testing
[2022-02-17T16:10:53.185] [ERROR] ma-core - update sla By SlaContract :sla not found testing testing testing
[2022-02-17T16:10:53.187] [ERROR] ma-core - update sla By SlaContract :sla not found NaN post 1234
[2022-02-17T16:10:53.193] [INFO] ma-core - delete slaContract success testing testing testing
[2022-02-17T16:10:53.195] [INFO] ma-core - delete slaContract success NaN post 1234
[2022-02-17T16:10:53.196] [ERROR] ma-core - delete SlaContract :slaContract not found testing testing testing
[2022-02-17T16:10:53.197] [ERROR] ma-core - delete SlaContract :slaContract not found NaN post 1234
[2022-02-17T16:10:53.209] [ERROR] ma-core - Get by Customer Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/slaContract/getAllSlaContractByCustomerId/getAllSlaContractByCustomerIdServiceTest.js:78:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-17T16:10:53.211] [INFO] ma-core - get slaContract By Customer success testing testing testing
[2022-02-17T16:10:53.213] [INFO] ma-core - get slaContract By Customer success NaN post 1234
[2022-02-17T16:10:53.214] [ERROR] ma-core - get slaContract By Customer :customer not found testing testing testing
[2022-02-17T16:10:53.215] [ERROR] ma-core - get slaContract By Customer :customer not found NaN post 1234
[2022-02-17T16:10:53.217] [INFO] ma-core - get slaContract By Id success testing testing testing
[2022-02-17T16:10:53.218] [INFO] ma-core - get slaContract By Id success NaN post 1234
[2022-02-17T16:10:53.220] [ERROR] ma-core - get slaContract By Id :slaContract not found testing testing testing
[2022-02-17T16:10:53.221] [ERROR] ma-core - get slaContract By Id :slaContract not found NaN post 1234
[2022-02-17T16:10:53.226] [INFO] ma-core - add SlaContract success testing testing testing
[2022-02-17T16:10:53.228] [INFO] ma-core - add SlaContract success NaN post 1234
[2022-02-17T16:10:53.229] [ERROR] ma-core - add SlaContract :missing property testing testing testing
[2022-02-17T16:10:53.231] [ERROR] ma-core - add SlaContract :missing property NaN post 1234
[2022-02-17T16:10:53.238] [INFO] ma-core - update slaContract By Customer success testing testing testing
[2022-02-17T16:10:53.240] [INFO] ma-core - update slaContract By Customer success NaN post 1234
[2022-02-17T16:10:53.241] [ERROR] ma-core - update slaContract By Customer :slaContract not found testing testing testing
[2022-02-17T16:10:53.242] [ERROR] ma-core - update slaContract By Customer :slaContract not found NaN post 1234
[2022-02-17T16:10:53.412] [ERROR] ma-core - Get by Customer Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/system/getAllSystemByCustomerId/getAllSystemByCustomerIdServiceTest.js:52:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-17T16:10:53.433] [ERROR] ma-core - Get Categories by Customer ID and Type ID Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/system/getCategoryByTypesByCustomer/getCategoryByTypesByCustomerServiceTest.js:122:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-17T16:10:53.466] [ERROR] ma-core - Get types by Customer ID Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/system/getTypeByCustomer/getTypesByCustomerServiceTest.js:122:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-17T16:10:53.482] [INFO] ma-core - get All Task success testing testing testing
[2022-02-17T16:10:53.483] [INFO] ma-core - get All Task success NaN post 1234
[2022-02-17T16:10:53.485] [ERROR] ma-core - get All Task :an error occured testing testing testing
[2022-02-17T16:10:53.487] [ERROR] ma-core - get All Task :an error occured NaN post 1234
[2022-02-17T16:10:53.490] [INFO] ma-core - get All Task By filter success testing testing testing
[2022-02-17T16:10:53.491] [ERROR] ma-core - get All Task By filter error :error testing testing testing
[2022-02-17T16:10:53.493] [INFO] ma-core - get All Task By filter success testing testing testing
[2022-02-17T16:10:53.494] [INFO] ma-core - get by id Task success testing testing testing
[2022-02-17T16:10:53.495] [INFO] ma-core - get by id Task success NaN post 1234
[2022-02-17T16:10:53.497] [ERROR] ma-core - get by id Task :task not found testing testing testing
[2022-02-17T16:10:53.499] [ERROR] ma-core - get by id Task :task not found testing testing testing
[2022-02-17T16:10:53.500] [ERROR] ma-core - get by id Task :task not found NaN post 1234
[2022-02-17T16:10:53.505] [INFO] ma-core - get All Task By filter success testing testing testing
[2022-02-17T16:10:53.507] [ERROR] ma-core - get All Task By filter error :error testing testing testing
[2022-02-17T16:10:53.508] [INFO] ma-core - get All Task By filter success testing testing testing
[2022-02-17T16:10:53.566] [INFO] ma-core - get All Task By ID success testing testing testing
[2022-02-17T16:10:53.592] [INFO] ma-core - get All Task success testing testing testing
[2022-02-17T16:10:53.602] [INFO] ma-core - get Created Tasks success testing testing testing
[2022-02-17T16:10:53.608] [INFO] ma-core - get Created Tasks success NaN post 1234
[2022-02-17T16:10:53.612] [ERROR] ma-core - get Created Tasks error : error testing testing testing
[2022-02-17T16:10:53.616] [ERROR] ma-core - get Created Tasks error : error NaN post 1234
[2022-02-17T16:10:53.625] [INFO] ma-core - add Task success testing testing testing
[2022-02-17T16:10:53.626] [INFO] ma-core - add Task success NaN post 1234
[2022-02-17T16:10:53.627] [ERROR] ma-core - add Task :missing property testing testing testing
[2022-02-17T16:10:53.629] [ERROR] ma-core - add Task :missing property NaN post 1234
[2022-02-17T16:10:53.637] [INFO] ma-core - add Many Task success testing testing testing
[2022-02-17T16:10:53.640] [INFO] ma-core - add Many Task success NaN post 1234
[2022-02-17T16:10:53.641] [ERROR] ma-core - add Many Task :missing property testing testing testing
[2022-02-17T16:10:53.643] [ERROR] ma-core - add Many Task :missing property NaN post 1234
[2022-02-17T16:10:53.650] [INFO] ma-core - update Task success testing testing testing
[2022-02-17T16:10:53.651] [INFO] ma-core - update Task success NaN post 1234
[2022-02-17T16:10:53.653] [ERROR] ma-core - update Task :task not found testing testing testing
[2022-02-17T16:10:53.654] [ERROR] ma-core - update Task :task not found NaN post 1234
[2022-02-17T16:10:53.655] [DEBUG] ma-core - Before sending Info !!
[2022-02-17T16:10:53.656] [DEBUG] ma-core - Before sending inside the producer !
[2022-02-17T16:10:53.661] [INFO] ma-core - Update Task Assignee success testing testing testing
[2022-02-17T16:10:53.663] [INFO] ma-core - Update Task Assignee Incomplete testing testing testing
[2022-02-17T16:10:53.664] [ERROR] ma-core - Update Task Assignee :task not found testing testing testing
[2022-02-17T16:10:53.673] [INFO] ma-core - Canceled the Task testing testing testing
[2022-02-17T16:10:53.674] [INFO] ma-core - Canceled the Task NaN post 1234
[2022-02-17T16:10:53.678] [ERROR] ma-core - Failed to Cancel the Task :failed to update the task testing testing testing
[2022-02-17T16:10:53.679] [ERROR] ma-core - Failed to Cancel the Task :failed to update the task NaN post 1234
[2022-02-17T16:10:53.681] [INFO] ma-core - Closed the Task testing testing testing
[2022-02-17T16:10:53.683] [INFO] ma-core - Closed the Task NaN post 1234
[2022-02-17T16:10:53.686] [ERROR] ma-core - Failed to reject the Task :failed to update the task testing testing testing
[2022-02-17T16:10:53.688] [ERROR] ma-core - Failed to reject the Task :failed to update the task NaN post 1234
[2022-02-17T16:10:53.690] [INFO] ma-core - Deleted the Task testing testing testing
[2022-02-17T16:10:53.691] [INFO] ma-core - Deleted the Task NaN post 1234
[2022-02-17T16:10:53.695] [ERROR] ma-core - Failed to delete the Task :failed to update the task testing testing testing
[2022-02-17T16:10:53.696] [ERROR] ma-core - Failed to delete the Task :failed to update the task NaN post 1234
[2022-02-17T16:10:53.699] [INFO] ma-core - Finished the Task testing testing testing
[2022-02-17T16:10:53.700] [INFO] ma-core - Finished the Task NaN post 1234
[2022-02-17T16:10:53.704] [ERROR] ma-core - Failed to finish the Task :failed to update the task testing testing testing
[2022-02-17T16:10:53.705] [ERROR] ma-core - Failed to finish the Task :failed to update the task NaN post 1234
[2022-02-17T16:10:53.707] [INFO] ma-core - Rejected the Task testing testing testing
[2022-02-17T16:10:53.709] [INFO] ma-core - Rejected the Task NaN post 1234
[2022-02-17T16:10:53.714] [ERROR] ma-core - Failed to reject the Task :failed to update the task testing testing testing
[2022-02-17T16:10:53.716] [ERROR] ma-core - Failed to reject the Task :failed to update the task NaN post 1234
[2022-02-17T16:10:53.719] [ERROR] ma-core - An unexpected error occurred during auto start task Error: WARNING: Date in past. Will never be fired.
    at CronTime.sendAt (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:148:12)
    at CronTime.getTimeout (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:175:29)
    at CronJob.start (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:613:31)
    at new CronJob (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:576:10)
    at module.exports (/home/azer/avaxia-monitpring-app/core-service/services/task/autoStartTaskCron.js:2:1041)
    at Object.exports.validateTask (/home/azer/avaxia-monitpring-app/core-service/controllers/task.controller.js:11:699)
    at async Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/task/updateState/validateTask.controller.test.js:51:5)
[2022-02-17T16:10:53.720] [INFO] ma-core - Validated the Task testing testing testing
[2022-02-17T16:10:53.722] [ERROR] ma-core - An unexpected error occurred during auto start task Error: WARNING: Date in past. Will never be fired.
    at CronTime.sendAt (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:148:12)
    at CronTime.getTimeout (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:175:29)
    at CronJob.start (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:613:31)
    at new CronJob (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:576:10)
    at module.exports (/home/azer/avaxia-monitpring-app/core-service/services/task/autoStartTaskCron.js:2:1041)
    at Object.exports.validateTask (/home/azer/avaxia-monitpring-app/core-service/controllers/task.controller.js:11:699)
    at async Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/task/updateState/validateTask.controller.test.js:95:5)
[2022-02-17T16:10:53.722] [INFO] ma-core - Validated the Task NaN post 1234
[2022-02-17T16:10:53.727] [ERROR] ma-core - An unexpected error occurred during auto start task Error: WARNING: Date in past. Will never be fired.
    at CronTime.sendAt (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:148:12)
    at CronTime.getTimeout (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:175:29)
    at CronJob.start (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:613:31)
    at new CronJob (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:576:10)
    at module.exports (/home/azer/avaxia-monitpring-app/core-service/services/task/autoStartTaskCron.js:2:1041)
    at Object.exports.validateTask (/home/azer/avaxia-monitpring-app/core-service/controllers/task.controller.js:11:699)
    at async Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/task/updateState/validateTask.controller.test.js:176:5)
[2022-02-17T16:10:53.727] [ERROR] ma-core - Failed to validate the Task :failed to update the task testing testing testing
[2022-02-17T16:10:53.730] [ERROR] ma-core - An unexpected error occurred during auto start task Error: WARNING: Date in past. Will never be fired.
    at CronTime.sendAt (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:148:12)
    at CronTime.getTimeout (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:175:29)
    at CronJob.start (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:613:31)
    at new CronJob (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:576:10)
    at module.exports (/home/azer/avaxia-monitpring-app/core-service/services/task/autoStartTaskCron.js:2:1041)
    at Object.exports.validateTask (/home/azer/avaxia-monitpring-app/core-service/controllers/task.controller.js:11:699)
    at async Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/task/updateState/validateTask.controller.test.js:219:5)
[2022-02-17T16:10:53.730] [ERROR] ma-core - Failed to validate the Task :failed to update the task NaN post 1234
[2022-02-17T16:10:53.734] [INFO] ma-core - update Task success testing testing testing
[2022-02-17T16:10:53.739] [INFO] ma-core - update Task success NaN post 1234
[2022-02-17T16:10:53.742] [ERROR] ma-core - update Task :You are not authorized to perform this action testing testing testing
[2022-02-17T16:10:53.745] [ERROR] ma-core - update Task :task not found NaN post 1234
[2022-02-17T16:10:53.809] [ERROR] ma-core - random Error
[2022-02-17T16:10:54.463] [ERROR] ma-core - random error
[2022-02-17T16:21:48.178] [ERROR] ma-core - formValidator in insert resultform validation : gStatus | taskId undefined testing testing testing
[2022-02-17T16:21:48.184] [ERROR] ma-core - formValidator in insert resultform validation : gStatus | taskId undefined testing testing testing
[2022-02-17T16:21:48.186] [ERROR] ma-core - formValidator in insert resultform validation : gStatus | taskId undefined testing testing testing
[2022-02-17T17:32:51.063] [INFO] ma-core - database URI mongodb://localhost:27017/core
[2022-02-17T17:32:51.694] [INFO] ma-core - server started at port 5000
[2022-02-17T17:32:51.715] [INFO] ma-core - mongodb conected
[2022-02-17T17:33:32.779] [INFO] ma-core - get All Active itOperation success /api/itoperation/getAllActive POST ::1
[2022-02-17T17:34:18.127] [INFO] ma-core - database URI mongodb://localhost:27017/core
[2022-02-17T17:34:18.798] [INFO] ma-core - server started at port 5000
[2022-02-17T17:34:18.817] [INFO] ma-core - mongodb conected
[2022-02-17T17:34:38.306] [INFO] ma-core - database URI mongodb://localhost:27017/core
[2022-02-17T17:34:38.942] [INFO] ma-core - server started at port 5000
[2022-02-17T17:34:38.963] [INFO] ma-core - mongodb conected
[2022-02-17T17:34:40.176] [INFO] ma-core - database URI mongodb://localhost:27017/core
[2022-02-17T17:34:40.873] [INFO] ma-core - server started at port 5000
[2022-02-17T17:34:40.901] [INFO] ma-core - mongodb conected
[2022-02-17T17:34:41.498] [INFO] ma-core - get All Active itOperation success /api/itoperation/getAllActive POST ::1
[2022-02-17T17:34:51.988] [INFO] ma-core - database URI mongodb://localhost:27017/core
[2022-02-17T17:34:52.758] [INFO] ma-core - server started at port 5000
[2022-02-17T17:34:52.784] [INFO] ma-core - mongodb conected
[2022-02-17T17:34:55.710] [INFO] ma-core - get All Active itOperation success /api/itoperation/getAllActive POST ::1
[2022-02-17T17:34:59.807] [INFO] ma-core - get All Active itOperation success /api/itoperation/getAllActive POST ::1
[2022-02-17T17:35:03.330] [INFO] ma-core - database URI mongodb://localhost:27017/core
[2022-02-17T17:35:04.101] [INFO] ma-core - server started at port 5000
[2022-02-17T17:35:04.121] [INFO] ma-core - mongodb conected
[2022-02-17T17:35:04.990] [INFO] ma-core - get All Active itOperation success /api/itoperation/getAllActive POST ::1
