[2022-01-10T15:27:42.501] [INFO] ma-core - database URI mongodb://localhost:27017/core
[2022-01-10T15:27:44.048] [INFO] ma-core - server started at port 5000
[2022-01-10T15:27:44.075] [INFO] ma-core - mongodb conected
[2022-01-10T15:27:44.154] [INFO] ma-core - add Client success testing testing testing
[2022-01-10T15:27:44.156] [ERROR] ma-core - add Client :missing property testing testing testing
[2022-01-10T15:27:44.158] [ERROR] ma-core - add Client :missing property NaN post 1234
[2022-01-10T15:27:44.170] [ERROR] ma-core - Delete Error : Error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/client/delete/deleteClient.service.test.js:62:33)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:27:44.172] [ERROR] ma-core - Delete Error : Error: random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/client/delete/deleteClient.service.test.js:72:33)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:27:44.195] [ERROR] ma-core - Get by System Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/client/getClientsBySystemId/getAllBySystemServiceTest.js:49:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:27:44.206] [ERROR] ma-core - Error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/client/update/updateClient.service.test.js:70:33)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:27:44.219] [INFO] ma-core - get all Customer success testing testing testing
[2022-01-10T15:27:44.221] [INFO] ma-core - get all Customer success NaN post 1234
[2022-01-10T15:27:44.222] [INFO] ma-core - get all Customer success testing testing testing
[2022-01-10T15:27:44.223] [INFO] ma-core - get all Customer error testing testing testing
[2022-01-10T15:27:44.225] [INFO] ma-core - get all Customer error NaN post 1234
[2022-01-10T15:27:44.235] [INFO] ma-core - get Customer error testing testing testing
[2022-01-10T15:27:44.240] [ERROR] ma-core - Error: random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/customer/getById/getByIdCustomer.service.test.js:88:24)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:27:44.254] [INFO] ma-core - add customer success testing testing testing
[2022-01-10T15:27:44.255] [ERROR] ma-core - add customer fail :missing property testing testing testing
[2022-01-10T15:27:44.365] [ERROR] ma-core - Delete Error : Error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/host/delete/deleteHost.service.test.js:72:33)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:27:44.373] [ERROR] ma-core - Get by System Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/host/getAllBySystem/getAllBySystemServiceTest.js:49:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:27:44.380] [ERROR] ma-core - Get by ID Error : Error: random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/host/getById/getByIdHost.service.test.js:58:24)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:27:44.387] [ERROR] ma-core - expected findOneAndUpdate to have been called exactly once, but it was called 0 times
[2022-01-10T15:27:44.396] [ERROR] ma-core - Update Error : Error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/host/update/updateHost.service.test.js:79:33)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:27:41.183] [INFO] ma-core - cancel itOperation success testing testing testing
[2022-01-10T15:27:41.183] [ERROR] ma-core - cancel ItOperation :itOperation not found testing testing testing
[2022-01-10T15:27:41.185] [INFO] ma-core - finish itOperation success testing testing testing
[2022-01-10T15:27:41.185] [ERROR] ma-core - finish ItOperation :itOperation not found testing testing testing
[2022-01-10T15:27:44.408] [INFO] ma-core - get All Active itOperation success testing testing testing
[2022-01-10T15:27:44.413] [INFO] ma-core - get All Archived itOperation success testing testing testing
[2022-01-10T15:27:44.420] [ERROR] ma-core - Error occur while Getting ItOperation By System Id : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/itOperation/getAllBySystem/getAllBySystemServiceTest.js:50:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:27:44.429] [INFO] ma-core - add ItOperation success testing testing testing
[2022-01-10T15:27:44.431] [ERROR] ma-core - add ItOperation fail :missing property testing testing testing
[2022-01-10T15:27:41.200] [INFO] ma-core - remind itOperation success testing testing testing
[2022-01-10T15:27:41.200] [ERROR] ma-core - remind ItOperation :itOperation not found testing testing testing
[2022-01-10T15:27:41.202] [INFO] ma-core - send changes itOperation success testing testing testing
[2022-01-10T15:27:41.202] [ERROR] ma-core - send changes ItOperation :itOperation not found testing testing testing
[2022-01-10T15:27:44.450] [INFO] ma-core - update itOperation success testing testing testing
[2022-01-10T15:27:44.452] [ERROR] ma-core - update ItOperation :itOperation not found testing testing testing
[2022-01-10T15:27:44.477] [INFO] ma-core - delete licence success testing testing testing
[2022-01-10T15:27:44.479] [INFO] ma-core - delete licence success NaN post 1234
[2022-01-10T15:27:44.481] [ERROR] ma-core - delete Licence :licence not found testing testing testing
[2022-01-10T15:27:44.483] [ERROR] ma-core - delete Licence :licence not found NaN post 1234
[2022-01-10T15:27:44.489] [INFO] ma-core - get latest customer licence By Id success testing testing testing
[2022-01-10T15:27:44.491] [INFO] ma-core - get latest customer licence By Id success NaN post 1234
[2022-01-10T15:27:44.493] [ERROR] ma-core - get licence By Id :Missing Customer ID NaN post 1234
[2022-01-10T15:27:44.494] [ERROR] ma-core - get licence By Id :Missing Customer ID testing testing testing
[2022-01-10T15:27:44.496] [ERROR] ma-core - get licence By Id :licence not found testing testing testing
[2022-01-10T15:27:44.498] [ERROR] ma-core - get licence By Id :licence not found NaN post 1234
[2022-01-10T15:27:44.501] [ERROR] ma-core - Error occur while Getting Licence By Customer Id : Error: random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/licence/getActiveLicence/getActiveLIcenceServiceTest.js:52:17)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:27:44.505] [ERROR] ma-core - Error occur while Getting Licence By Customer Id : Error: random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/licence/getByCustomer/getByCustomerLicence.service.test.js:61:17)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:27:44.508] [INFO] ma-core - get licence By Id success testing testing testing
[2022-01-10T15:27:44.510] [INFO] ma-core - get licence By Id success NaN post 1234
[2022-01-10T15:27:44.511] [ERROR] ma-core - get licence By Id :licence not found testing testing testing
[2022-01-10T15:27:44.513] [ERROR] ma-core - get licence By Id :licence not found NaN post 1234
[2022-01-10T15:27:44.522] [INFO] ma-core - add Licence success testing testing testing
[2022-01-10T15:27:44.523] [INFO] ma-core - add Licence success NaN post 1234
[2022-01-10T15:27:44.525] [ERROR] ma-core - add Licence :missing property testing testing testing
[2022-01-10T15:27:44.527] [ERROR] ma-core - add Licence :missing property NaN post 1234
[2022-01-10T15:27:44.536] [INFO] ma-core - update licence By Customer success testing testing testing
[2022-01-10T15:27:44.540] [INFO] ma-core - update licence By Customer success NaN post 1234
[2022-01-10T15:27:44.542] [ERROR] ma-core - update licence By Customer :licence not found testing testing testing
[2022-01-10T15:27:44.543] [ERROR] ma-core - update licence By Customer :licence not found NaN post 1234
[2022-01-10T15:27:44.561] [ERROR] ma-core - delete Map By Id :MAP not found testing testing testing
[2022-01-10T15:27:44.564] [ERROR] ma-core - delete Map By Id :missing ID testing testing testing
[2022-01-10T15:27:44.565] [ERROR] ma-core - delete Map By Id :missing ID testing testing testing
[2022-01-10T15:27:44.569] [ERROR] ma-core - delete Map By Id :missing ID NaN post 1234
[2022-01-10T15:27:44.587] [ERROR] ma-core - Get by System Error : TypeError: moment(...).tz(...).format is not a function
    at /home/azer/avaxia-monitpring-app/core-service/services/map/getBySystemId.js:2:1950
    at Array.map (<anonymous>)
    at module.exports (/home/azer/avaxia-monitpring-app/core-service/services/map/getBySystemId.js:2:1771)
    at async Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/map/getAllBySystem/getAllBySystemServiceTest.js:71:17)
[2022-01-10T15:27:44.591] [ERROR] ma-core - Get by System Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/map/getAllBySystem/getAllBySystemServiceTest.js:98:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:27:44.618] [INFO] ma-core - delete module success testing testing testing
[2022-01-10T15:27:44.619] [INFO] ma-core - delete module success NaN post 1234
[2022-01-10T15:27:44.621] [ERROR] ma-core - delete Module :module not found testing testing testing
[2022-01-10T15:27:44.622] [ERROR] ma-core - delete Module :module not found NaN post 1234
[2022-01-10T15:27:44.624] [ERROR] ma-core - delete Module :missing ID testing testing testing
[2022-01-10T15:27:44.625] [ERROR] ma-core - delete Module :missing ID testing testing testing
[2022-01-10T15:27:44.631] [INFO] ma-core - get All Basic Module success testing testing testing
[2022-01-10T15:27:44.633] [INFO] ma-core - get All Basic Module success NaN post 1234
[2022-01-10T15:27:44.635] [ERROR] ma-core - get All Basic Module :missing property testing testing testing
[2022-01-10T15:27:44.637] [ERROR] ma-core - get All Basic Module :missing property NaN post 1234
[2022-01-10T15:27:44.638] [INFO] ma-core - get All Module success testing testing testing
[2022-01-10T15:27:44.640] [INFO] ma-core - get All Module success NaN post 1234
[2022-01-10T15:27:44.645] [ERROR] ma-core - get All Module :missing property testing testing testing
[2022-01-10T15:27:44.648] [ERROR] ma-core - get All Module :missing property NaN post 1234
[2022-01-10T15:27:44.654] [INFO] ma-core - get module By Id success testing testing testing
[2022-01-10T15:27:44.655] [INFO] ma-core - get module By Id success NaN post 1234
[2022-01-10T15:27:44.656] [ERROR] ma-core - get module By Id :module not found testing testing testing
[2022-01-10T15:27:44.657] [ERROR] ma-core - get module By Id :module not found testing testing testing
[2022-01-10T15:27:44.660] [ERROR] ma-core - get module By Id :module not found NaN post 1234
[2022-01-10T15:27:44.668] [INFO] ma-core - add Module success testing testing testing
[2022-01-10T15:27:44.670] [INFO] ma-core - add Module success NaN post 1234
[2022-01-10T15:27:44.671] [ERROR] ma-core - add Module :missing property testing testing testing
[2022-01-10T15:27:44.673] [ERROR] ma-core - add Module :missing property NaN post 1234
[2022-01-10T15:27:44.678] [INFO] ma-core - update module By Customer success testing testing testing
[2022-01-10T15:27:44.679] [INFO] ma-core - update module By Customer success NaN post 1234
[2022-01-10T15:27:44.681] [ERROR] ma-core - update module By Customer :module not found testing testing testing
[2022-01-10T15:27:44.683] [ERROR] ma-core - update module By Customer :module not found testing testing testing
[2022-01-10T15:27:44.686] [ERROR] ma-core - update module By Customer :module not found NaN post 1234
[2022-01-10T15:27:44.760] [INFO] ma-core - get All nomenclature success testing testing testing
[2022-01-10T15:27:44.761] [INFO] ma-core - get All nomenclature success testing testing testing
[2022-01-10T15:27:44.763] [INFO] ma-core - get All nomenclature success NaN post 1234
[2022-01-10T15:27:44.764] [ERROR] ma-core - get All nomenclature :get All nomenclature : testing testing testing
[2022-01-10T15:27:44.766] [ERROR] ma-core - get All nomenclature :get All nomenclature : NaN post 1234
[2022-01-10T15:27:44.792] [INFO] ma-core - delete Result Form success testing testing testing
[2022-01-10T15:27:44.793] [INFO] ma-core - delete Result Form success NaN post 1234
[2022-01-10T15:27:44.795] [ERROR] ma-core - delete Result Form :task not found testing testing testing
[2022-01-10T15:27:44.796] [ERROR] ma-core - delete Result Form :task not found NaN post 1234
[2022-01-10T15:27:44.807] [INFO] ma-core - get all result form success testing testing testing
[2022-01-10T15:27:44.809] [INFO] ma-core - get all result form success testing testing testing
[2022-01-10T15:27:44.811] [INFO] ma-core - get all result form success NaN post 1234
[2022-01-10T15:27:44.812] [ERROR] ma-core - get All result form :missing property testing testing testing
[2022-01-10T15:27:44.814] [ERROR] ma-core - get All result form :missing property NaN post 1234
[2022-01-10T15:27:44.819] [INFO] ma-core - get by id Result Form testing testing testing
[2022-01-10T15:27:44.821] [INFO] ma-core - get by id Result Form NaN post 1234
[2022-01-10T15:27:44.822] [ERROR] ma-core - get by id Result Form :task not found testing testing testing
[2022-01-10T15:27:44.823] [ERROR] ma-core - get by id Result Form :task not found NaN post 1234
[2022-01-10T15:27:44.829] [INFO] ma-core - add result form success testing testing testing
[2022-01-10T15:27:44.830] [INFO] ma-core - add result form success NaN post 1234
[2022-01-10T15:27:44.832] [ERROR] ma-core - add result form :missing property testing testing testing
[2022-01-10T15:27:44.837] [ERROR] ma-core - add result form :missing property NaN post 1234
[2022-01-10T15:27:44.841] [INFO] ma-core - update Result Form success testing testing testing
[2022-01-10T15:27:44.843] [INFO] ma-core - update Result Form success NaN post 1234
[2022-01-10T15:27:44.845] [ERROR] ma-core - update Result Form  :task not found testing testing testing
[2022-01-10T15:27:44.846] [ERROR] ma-core - update Result Form  :task not found NaN post 1234
[2022-01-10T15:27:44.853] [INFO] ma-core - delete Role success testing testing testing
[2022-01-10T15:27:44.854] [INFO] ma-core - delete Role success NaN post 1234
[2022-01-10T15:27:44.855] [ERROR] ma-core - delete Role :role not found testing testing testing
[2022-01-10T15:27:44.857] [ERROR] ma-core - delete Role :role not found NaN post 1234
[2022-01-10T15:27:44.858] [ERROR] ma-core - delete Role :missing ID testing testing testing
[2022-01-10T15:27:44.860] [ERROR] ma-core - delete Role :missing ID testing testing testing
[2022-01-10T15:27:44.867] [INFO] ma-core - get All Role success testing testing testing
[2022-01-10T15:27:44.869] [INFO] ma-core - get All Role success NaN post 1234
[2022-01-10T15:27:44.870] [ERROR] ma-core - get All Role :missing property testing testing testing
[2022-01-10T15:27:44.872] [ERROR] ma-core - get All Role :missing property NaN post 1234
[2022-01-10T15:27:44.876] [INFO] ma-core - get by id Role success testing testing testing
[2022-01-10T15:27:44.877] [INFO] ma-core - get by id Role success NaN post 1234
[2022-01-10T15:27:44.879] [ERROR] ma-core - get by id Role :role not found testing testing testing
[2022-01-10T15:27:44.880] [ERROR] ma-core - get by id Role :role not found testing testing testing
[2022-01-10T15:27:44.883] [ERROR] ma-core - get by id Role :role not found NaN post 1234
[2022-01-10T15:27:44.892] [INFO] ma-core - get by user Role success testing testing testing
[2022-01-10T15:27:44.893] [INFO] ma-core - get by user Role success NaN get 1234
[2022-01-10T15:27:44.897] [ERROR] ma-core - get by user Role :user not found testing testing testing
[2022-01-10T15:27:44.898] [ERROR] ma-core - get by user Role :role not found testing testing testing
[2022-01-10T15:27:44.902] [ERROR] ma-core - get by user Role :role not found NaN get 1234
[2022-01-10T15:27:44.904] [INFO] ma-core - add Role success testing testing testing
[2022-01-10T15:27:44.905] [ERROR] ma-core - add Role :missing property testing testing testing
[2022-01-10T15:27:44.906] [INFO] ma-core - add Role success NaN post 1234
[2022-01-10T15:27:44.908] [ERROR] ma-core - add Role :missing property NaN post 1234
[2022-01-10T15:27:44.919] [INFO] ma-core - update Role success testing testing testing
[2022-01-10T15:27:44.920] [INFO] ma-core - update Role success NaN post 1234
[2022-01-10T15:27:44.921] [ERROR] ma-core - update Role :role not found testing testing testing
[2022-01-10T15:27:44.923] [ERROR] ma-core - update Role :role not found testing testing testing
[2022-01-10T15:27:44.925] [ERROR] ma-core - update Role :role not found NaN post 1234
[2022-01-10T15:27:44.932] [INFO] ma-core - add Role History success testing testing testing
[2022-01-10T15:27:44.934] [INFO] ma-core - add Role History success NaN post 1234
[2022-01-10T15:27:44.938] [ERROR] ma-core - add Client :missing property testing testing testing
[2022-01-10T15:27:44.940] [ERROR] ma-core - add Client :missing property NaN post 1234
[2022-01-10T15:27:44.967] [ERROR] ma-core - 
[2022-01-10T15:27:44.981] [INFO] ma-core - Get all shifts success testing testing testing
[2022-01-10T15:27:45.002] [INFO] ma-core - Get all members success testing testing testing
[2022-01-10T15:27:45.025] [INFO] ma-core - delete sla success testing testing testing
[2022-01-10T15:27:45.026] [INFO] ma-core - delete sla success NaN post 1234
[2022-01-10T15:27:45.028] [ERROR] ma-core - delete Sla :sla not found testing testing testing
[2022-01-10T15:27:45.029] [ERROR] ma-core - delete Sla :sla not found testing testing testing
[2022-01-10T15:27:45.032] [ERROR] ma-core - delete Sla :sla not found NaN post 1234
[2022-01-10T15:27:45.040] [INFO] ma-core - get sla By Id success testing testing testing
[2022-01-10T15:27:45.046] [INFO] ma-core - get sla By Id success NaN post 1234
[2022-01-10T15:27:45.048] [ERROR] ma-core - get sla By Id :sla not found testing testing testing
[2022-01-10T15:27:45.052] [ERROR] ma-core - get sla By Id :sla not found testing testing testing
[2022-01-10T15:27:45.053] [ERROR] ma-core - get sla By Id :sla not found NaN post 1234
[2022-01-10T15:27:45.060] [ERROR] ma-core - Error occur while Getting Sla By slaContract Id : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/sla/getByslaContract/getslaBySlaContract.service.test.js:70:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:27:45.068] [INFO] ma-core - add Sla success testing testing testing
[2022-01-10T15:27:45.069] [INFO] ma-core - add Sla success NaN post 1234
[2022-01-10T15:27:45.070] [ERROR] ma-core - add Sla :missing property testing testing testing
[2022-01-10T15:27:45.073] [ERROR] ma-core - add Sla :missing property NaN post 1234
[2022-01-10T15:27:45.087] [INFO] ma-core - update sla By SlaContract success testing testing testing
[2022-01-10T15:27:45.089] [INFO] ma-core - update sla By SlaContract success NaN post 1234
[2022-01-10T15:27:45.090] [ERROR] ma-core - update sla By SlaContract :sla not found testing testing testing
[2022-01-10T15:27:45.092] [ERROR] ma-core - update sla By SlaContract :sla not found testing testing testing
[2022-01-10T15:27:45.093] [ERROR] ma-core - update sla By SlaContract :sla not found NaN post 1234
[2022-01-10T15:27:45.102] [INFO] ma-core - delete slaContract success testing testing testing
[2022-01-10T15:27:45.103] [INFO] ma-core - delete slaContract success NaN post 1234
[2022-01-10T15:27:45.104] [ERROR] ma-core - delete SlaContract :slaContract not found testing testing testing
[2022-01-10T15:27:45.106] [ERROR] ma-core - delete SlaContract :slaContract not found NaN post 1234
[2022-01-10T15:27:45.119] [ERROR] ma-core - Get by Customer Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/slaContract/getAllSlaContractByCustomerId/getAllSlaContractByCustomerIdServiceTest.js:78:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:27:45.121] [INFO] ma-core - get slaContract By Customer success testing testing testing
[2022-01-10T15:27:45.123] [INFO] ma-core - get slaContract By Customer success NaN post 1234
[2022-01-10T15:27:45.125] [ERROR] ma-core - get slaContract By Customer :customer not found testing testing testing
[2022-01-10T15:27:45.126] [ERROR] ma-core - get slaContract By Customer :customer not found NaN post 1234
[2022-01-10T15:27:45.128] [INFO] ma-core - get slaContract By Id success testing testing testing
[2022-01-10T15:27:45.130] [INFO] ma-core - get slaContract By Id success NaN post 1234
[2022-01-10T15:27:45.131] [ERROR] ma-core - get slaContract By Id :slaContract not found testing testing testing
[2022-01-10T15:27:45.133] [ERROR] ma-core - get slaContract By Id :slaContract not found NaN post 1234
[2022-01-10T15:27:45.139] [INFO] ma-core - add SlaContract success testing testing testing
[2022-01-10T15:27:45.140] [INFO] ma-core - add SlaContract success NaN post 1234
[2022-01-10T15:27:45.141] [ERROR] ma-core - add SlaContract :missing property testing testing testing
[2022-01-10T15:27:45.143] [ERROR] ma-core - add SlaContract :missing property NaN post 1234
[2022-01-10T15:27:45.157] [INFO] ma-core - update slaContract By Customer success testing testing testing
[2022-01-10T15:27:45.158] [INFO] ma-core - update slaContract By Customer success NaN post 1234
[2022-01-10T15:27:45.159] [ERROR] ma-core - update slaContract By Customer :slaContract not found testing testing testing
[2022-01-10T15:27:45.161] [ERROR] ma-core - update slaContract By Customer :slaContract not found NaN post 1234
[2022-01-10T15:27:45.262] [ERROR] ma-core - Get by Customer Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/system/getAllSystemByCustomerId/getAllSystemByCustomerIdServiceTest.js:52:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:27:45.285] [ERROR] ma-core - Get Categories by Customer ID and Type ID Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/system/getCategoryByTypesByCustomer/getCategoryByTypesByCustomerServiceTest.js:122:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:27:45.310] [ERROR] ma-core - Get types by Customer ID Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/system/getTypeByCustomer/getTypesByCustomerServiceTest.js:122:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:27:45.333] [INFO] ma-core - get All Task success testing testing testing
[2022-01-10T15:27:45.335] [INFO] ma-core - get All Task success NaN post 1234
[2022-01-10T15:27:45.339] [INFO] ma-core - get All Task By filter success testing testing testing
[2022-01-10T15:27:45.340] [ERROR] ma-core - get All Task By filter error :error testing testing testing
[2022-01-10T15:27:45.341] [INFO] ma-core - get All Task By filter success testing testing testing
[2022-01-10T15:27:45.343] [INFO] ma-core - get by id Task success testing testing testing
[2022-01-10T15:27:45.344] [INFO] ma-core - get by id Task success NaN post 1234
[2022-01-10T15:27:45.346] [ERROR] ma-core - get by id Task :task not found testing testing testing
[2022-01-10T15:27:45.347] [ERROR] ma-core - get by id Task :task not found NaN post 1234
[2022-01-10T15:27:45.353] [INFO] ma-core - get All Task By filter success testing testing testing
[2022-01-10T15:27:45.354] [ERROR] ma-core - get All Task By filter error :error testing testing testing
[2022-01-10T15:27:45.355] [INFO] ma-core - get All Task By filter success testing testing testing
[2022-01-10T15:27:45.415] [INFO] ma-core - get All Task By ID success testing testing testing
[2022-01-10T15:27:45.435] [INFO] ma-core - get All Task success testing testing testing
[2022-01-10T15:27:45.453] [INFO] ma-core - get Created Tasks success testing testing testing
[2022-01-10T15:27:45.460] [INFO] ma-core - get Created Tasks success NaN post 1234
[2022-01-10T15:27:45.466] [ERROR] ma-core - get Created Tasks error : error testing testing testing
[2022-01-10T15:27:45.471] [ERROR] ma-core - get Created Tasks error : error NaN post 1234
[2022-01-10T15:27:45.480] [INFO] ma-core - add Task success testing testing testing
[2022-01-10T15:27:45.484] [INFO] ma-core - add Task success NaN post 1234
[2022-01-10T15:27:45.487] [ERROR] ma-core - add Task :missing property testing testing testing
[2022-01-10T15:27:45.491] [ERROR] ma-core - add Task :missing property NaN post 1234
[2022-01-10T15:27:45.514] [INFO] ma-core - add Many Task success testing testing testing
[2022-01-10T15:27:45.520] [INFO] ma-core - add Many Task success NaN post 1234
[2022-01-10T15:27:45.524] [ERROR] ma-core - add Many Task :missing property testing testing testing
[2022-01-10T15:27:45.526] [ERROR] ma-core - add Many Task :missing property NaN post 1234
[2022-01-10T15:27:45.540] [INFO] ma-core - update Task success testing testing testing
[2022-01-10T15:27:45.542] [INFO] ma-core - update Task success NaN post 1234
[2022-01-10T15:27:45.544] [ERROR] ma-core - update Task :task not found testing testing testing
[2022-01-10T15:27:45.546] [ERROR] ma-core - update Task :task not found NaN post 1234
[2022-01-10T15:27:45.547] [DEBUG] ma-core - Before sending Info !!
[2022-01-10T15:27:45.547] [DEBUG] ma-core - Before sending inside the producer !
[2022-01-10T15:27:45.574] [INFO] ma-core - Update Task Assignee success testing testing testing
[2022-01-10T15:27:45.575] [INFO] ma-core - Update Task Assignee Incomplete testing testing testing
[2022-01-10T15:27:45.593] [ERROR] ma-core - Update Task Assignee :task not found testing testing testing
[2022-01-10T15:27:45.605] [INFO] ma-core - Canceled the Task testing testing testing
[2022-01-10T15:27:45.608] [INFO] ma-core - Canceled the Task NaN post 1234
[2022-01-10T15:27:45.612] [ERROR] ma-core - Failed to Cancel the Task :failed to update the task testing testing testing
[2022-01-10T15:27:45.614] [ERROR] ma-core - Failed to Cancel the Task :failed to update the task NaN post 1234
[2022-01-10T15:27:45.619] [INFO] ma-core - Closed the Task testing testing testing
[2022-01-10T15:27:45.622] [INFO] ma-core - Closed the Task NaN post 1234
[2022-01-10T15:27:45.627] [ERROR] ma-core - Failed to reject the Task :failed to update the task testing testing testing
[2022-01-10T15:27:45.628] [ERROR] ma-core - Failed to reject the Task :failed to update the task NaN post 1234
[2022-01-10T15:27:45.630] [INFO] ma-core - Deleted the Task testing testing testing
[2022-01-10T15:27:45.634] [INFO] ma-core - Deleted the Task NaN post 1234
[2022-01-10T15:27:45.640] [ERROR] ma-core - Failed to delete the Task :failed to update the task testing testing testing
[2022-01-10T15:27:45.642] [ERROR] ma-core - Failed to delete the Task :failed to update the task NaN post 1234
[2022-01-10T15:27:45.644] [INFO] ma-core - Finished the Task testing testing testing
[2022-01-10T15:27:45.647] [INFO] ma-core - Finished the Task NaN post 1234
[2022-01-10T15:27:45.655] [ERROR] ma-core - Failed to finish the Task :failed to update the task testing testing testing
[2022-01-10T15:27:45.657] [ERROR] ma-core - Failed to finish the Task :failed to update the task NaN post 1234
[2022-01-10T15:27:45.659] [INFO] ma-core - Rejected the Task testing testing testing
[2022-01-10T15:27:45.661] [INFO] ma-core - Rejected the Task NaN post 1234
[2022-01-10T15:27:45.670] [ERROR] ma-core - Failed to reject the Task :failed to update the task testing testing testing
[2022-01-10T15:27:45.673] [ERROR] ma-core - Failed to reject the Task :failed to update the task NaN post 1234
[2022-01-10T15:27:45.677] [ERROR] ma-core - An unexpected error occurred during auto start task Error: WARNING: Date in past. Will never be fired.
    at CronTime.sendAt (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:148:12)
    at CronTime.getTimeout (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:175:29)
    at CronJob.start (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:613:31)
    at new CronJob (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:576:10)
    at module.exports (/home/azer/avaxia-monitpring-app/core-service/services/task/autoStartTaskCron.js:2:1041)
    at Object.exports.validateTask (/home/azer/avaxia-monitpring-app/core-service/controllers/task.controller.js:11:699)
    at async Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/task/updateState/validateTask.controller.test.js:51:5)
[2022-01-10T15:27:45.677] [INFO] ma-core - Validated the Task testing testing testing
[2022-01-10T15:27:45.680] [ERROR] ma-core - An unexpected error occurred during auto start task Error: WARNING: Date in past. Will never be fired.
    at CronTime.sendAt (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:148:12)
    at CronTime.getTimeout (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:175:29)
    at CronJob.start (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:613:31)
    at new CronJob (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:576:10)
    at module.exports (/home/azer/avaxia-monitpring-app/core-service/services/task/autoStartTaskCron.js:2:1041)
    at Object.exports.validateTask (/home/azer/avaxia-monitpring-app/core-service/controllers/task.controller.js:11:699)
    at async Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/task/updateState/validateTask.controller.test.js:95:5)
[2022-01-10T15:27:45.682] [INFO] ma-core - Validated the Task NaN post 1234
[2022-01-10T15:27:45.693] [ERROR] ma-core - An unexpected error occurred during auto start task Error: WARNING: Date in past. Will never be fired.
    at CronTime.sendAt (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:148:12)
    at CronTime.getTimeout (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:175:29)
    at CronJob.start (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:613:31)
    at new CronJob (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:576:10)
    at module.exports (/home/azer/avaxia-monitpring-app/core-service/services/task/autoStartTaskCron.js:2:1041)
    at Object.exports.validateTask (/home/azer/avaxia-monitpring-app/core-service/controllers/task.controller.js:11:699)
    at async Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/task/updateState/validateTask.controller.test.js:176:5)
[2022-01-10T15:27:45.693] [ERROR] ma-core - Failed to validate the Task :failed to update the task testing testing testing
[2022-01-10T15:27:45.696] [ERROR] ma-core - An unexpected error occurred during auto start task Error: WARNING: Date in past. Will never be fired.
    at CronTime.sendAt (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:148:12)
    at CronTime.getTimeout (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:175:29)
    at CronJob.start (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:613:31)
    at new CronJob (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:576:10)
    at module.exports (/home/azer/avaxia-monitpring-app/core-service/services/task/autoStartTaskCron.js:2:1041)
    at Object.exports.validateTask (/home/azer/avaxia-monitpring-app/core-service/controllers/task.controller.js:11:699)
    at async Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/task/updateState/validateTask.controller.test.js:219:5)
[2022-01-10T15:27:45.697] [ERROR] ma-core - Failed to validate the Task :failed to update the task NaN post 1234
[2022-01-10T15:27:45.707] [INFO] ma-core - update Task success testing testing testing
[2022-01-10T15:27:45.711] [INFO] ma-core - update Task success NaN post 1234
[2022-01-10T15:27:45.716] [ERROR] ma-core - update Task :You are not authorized to perform this action testing testing testing
[2022-01-10T15:27:45.723] [ERROR] ma-core - update Task :task not found NaN post 1234
[2022-01-10T15:27:45.807] [ERROR] ma-core - random Error
[2022-01-10T15:27:46.523] [ERROR] ma-core - random error
[2022-01-10T15:36:30.599] [INFO] ma-core - database URI mongodb://localhost:27017/core
[2022-01-10T15:36:31.688] [INFO] ma-core - server started at port 5000
[2022-01-10T15:36:31.762] [INFO] ma-core - mongodb conected
[2022-01-10T15:36:31.844] [INFO] ma-core - add Client success testing testing testing
[2022-01-10T15:36:31.845] [ERROR] ma-core - add Client :missing property testing testing testing
[2022-01-10T15:36:31.848] [ERROR] ma-core - add Client :missing property NaN post 1234
[2022-01-10T15:36:31.860] [ERROR] ma-core - Delete Error : Error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/client/delete/deleteClient.service.test.js:62:33)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:36:31.862] [ERROR] ma-core - Delete Error : Error: random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/client/delete/deleteClient.service.test.js:72:33)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:36:31.890] [ERROR] ma-core - Get by System Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/client/getClientsBySystemId/getAllBySystemServiceTest.js:49:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:36:31.898] [ERROR] ma-core - Error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/client/update/updateClient.service.test.js:70:33)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:36:31.912] [INFO] ma-core - get all Customer success testing testing testing
[2022-01-10T15:36:31.914] [INFO] ma-core - get all Customer success NaN post 1234
[2022-01-10T15:36:31.917] [INFO] ma-core - get all Customer success testing testing testing
[2022-01-10T15:36:31.919] [INFO] ma-core - get all Customer error testing testing testing
[2022-01-10T15:36:31.921] [INFO] ma-core - get all Customer error NaN post 1234
[2022-01-10T15:36:31.935] [INFO] ma-core - get Customer error testing testing testing
[2022-01-10T15:36:31.940] [ERROR] ma-core - Error: random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/customer/getById/getByIdCustomer.service.test.js:88:24)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:36:31.955] [INFO] ma-core - add customer success testing testing testing
[2022-01-10T15:36:31.957] [ERROR] ma-core - add customer fail :missing property testing testing testing
[2022-01-10T15:36:32.076] [ERROR] ma-core - Delete Error : Error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/host/delete/deleteHost.service.test.js:72:33)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:36:32.085] [ERROR] ma-core - Get by System Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/host/getAllBySystem/getAllBySystemServiceTest.js:49:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:36:32.092] [ERROR] ma-core - Get by ID Error : Error: random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/host/getById/getByIdHost.service.test.js:58:24)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:36:32.099] [ERROR] ma-core - expected findOneAndUpdate to have been called exactly once, but it was called 0 times
[2022-01-10T15:36:32.111] [ERROR] ma-core - Update Error : Error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/host/update/updateHost.service.test.js:79:33)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:36:29.585] [INFO] ma-core - cancel itOperation success testing testing testing
[2022-01-10T15:36:29.585] [ERROR] ma-core - cancel ItOperation :itOperation not found testing testing testing
[2022-01-10T15:36:29.587] [INFO] ma-core - finish itOperation success testing testing testing
[2022-01-10T15:36:29.587] [ERROR] ma-core - finish ItOperation :itOperation not found testing testing testing
[2022-01-10T15:36:32.124] [INFO] ma-core - get All Active itOperation success testing testing testing
[2022-01-10T15:36:32.128] [INFO] ma-core - get All Archived itOperation success testing testing testing
[2022-01-10T15:36:32.137] [ERROR] ma-core - Error occur while Getting ItOperation By System Id : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/itOperation/getAllBySystem/getAllBySystemServiceTest.js:50:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:36:32.147] [INFO] ma-core - add ItOperation success testing testing testing
[2022-01-10T15:36:32.150] [ERROR] ma-core - add ItOperation fail :missing property testing testing testing
[2022-01-10T15:36:29.601] [INFO] ma-core - remind itOperation success testing testing testing
[2022-01-10T15:36:29.601] [ERROR] ma-core - remind ItOperation :itOperation not found testing testing testing
[2022-01-10T15:36:29.602] [INFO] ma-core - send changes itOperation success testing testing testing
[2022-01-10T15:36:29.602] [ERROR] ma-core - send changes ItOperation :itOperation not found testing testing testing
[2022-01-10T15:36:32.172] [INFO] ma-core - update itOperation success testing testing testing
[2022-01-10T15:36:32.174] [ERROR] ma-core - update ItOperation :itOperation not found testing testing testing
[2022-01-10T15:36:32.205] [INFO] ma-core - delete licence success testing testing testing
[2022-01-10T15:36:32.207] [INFO] ma-core - delete licence success NaN post 1234
[2022-01-10T15:36:32.208] [ERROR] ma-core - delete Licence :licence not found testing testing testing
[2022-01-10T15:36:32.210] [ERROR] ma-core - delete Licence :licence not found NaN post 1234
[2022-01-10T15:36:32.220] [INFO] ma-core - get latest customer licence By Id success testing testing testing
[2022-01-10T15:36:32.223] [INFO] ma-core - get latest customer licence By Id success NaN post 1234
[2022-01-10T15:36:32.224] [ERROR] ma-core - get licence By Id :Missing Customer ID NaN post 1234
[2022-01-10T15:36:32.226] [ERROR] ma-core - get licence By Id :Missing Customer ID testing testing testing
[2022-01-10T15:36:32.227] [ERROR] ma-core - get licence By Id :licence not found testing testing testing
[2022-01-10T15:36:32.228] [ERROR] ma-core - get licence By Id :licence not found NaN post 1234
[2022-01-10T15:36:32.233] [ERROR] ma-core - Error occur while Getting Licence By Customer Id : Error: random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/licence/getActiveLicence/getActiveLIcenceServiceTest.js:52:17)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:36:32.237] [ERROR] ma-core - Error occur while Getting Licence By Customer Id : Error: random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/licence/getByCustomer/getByCustomerLicence.service.test.js:61:17)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:36:32.241] [INFO] ma-core - get licence By Id success testing testing testing
[2022-01-10T15:36:32.242] [INFO] ma-core - get licence By Id success NaN post 1234
[2022-01-10T15:36:32.243] [ERROR] ma-core - get licence By Id :licence not found testing testing testing
[2022-01-10T15:36:32.245] [ERROR] ma-core - get licence By Id :licence not found NaN post 1234
[2022-01-10T15:36:32.256] [INFO] ma-core - add Licence success testing testing testing
[2022-01-10T15:36:32.258] [INFO] ma-core - add Licence success NaN post 1234
[2022-01-10T15:36:32.260] [ERROR] ma-core - add Licence :missing property testing testing testing
[2022-01-10T15:36:32.261] [ERROR] ma-core - add Licence :missing property NaN post 1234
[2022-01-10T15:36:32.273] [INFO] ma-core - update licence By Customer success testing testing testing
[2022-01-10T15:36:32.274] [INFO] ma-core - update licence By Customer success NaN post 1234
[2022-01-10T15:36:32.276] [ERROR] ma-core - update licence By Customer :licence not found testing testing testing
[2022-01-10T15:36:32.277] [ERROR] ma-core - update licence By Customer :licence not found NaN post 1234
[2022-01-10T15:36:32.303] [ERROR] ma-core - delete Map By Id :MAP not found testing testing testing
[2022-01-10T15:36:32.306] [ERROR] ma-core - delete Map By Id :missing ID testing testing testing
[2022-01-10T15:36:32.307] [ERROR] ma-core - delete Map By Id :missing ID testing testing testing
[2022-01-10T15:36:32.309] [ERROR] ma-core - delete Map By Id :missing ID NaN post 1234
[2022-01-10T15:36:32.328] [ERROR] ma-core - Get by System Error : TypeError: moment(...).tz(...).format is not a function
    at /home/azer/avaxia-monitpring-app/core-service/services/map/getBySystemId.js:2:1950
    at Array.map (<anonymous>)
    at module.exports (/home/azer/avaxia-monitpring-app/core-service/services/map/getBySystemId.js:2:1771)
    at async Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/map/getAllBySystem/getAllBySystemServiceTest.js:71:17)
[2022-01-10T15:36:32.334] [ERROR] ma-core - Get by System Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/map/getAllBySystem/getAllBySystemServiceTest.js:98:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:36:32.360] [INFO] ma-core - delete module success testing testing testing
[2022-01-10T15:36:32.362] [INFO] ma-core - delete module success NaN post 1234
[2022-01-10T15:36:32.366] [ERROR] ma-core - delete Module :module not found testing testing testing
[2022-01-10T15:36:32.368] [ERROR] ma-core - delete Module :module not found NaN post 1234
[2022-01-10T15:36:32.371] [ERROR] ma-core - delete Module :missing ID testing testing testing
[2022-01-10T15:36:32.372] [ERROR] ma-core - delete Module :missing ID testing testing testing
[2022-01-10T15:36:32.377] [INFO] ma-core - get All Basic Module success testing testing testing
[2022-01-10T15:36:32.379] [INFO] ma-core - get All Basic Module success NaN post 1234
[2022-01-10T15:36:32.382] [ERROR] ma-core - get All Basic Module :missing property testing testing testing
[2022-01-10T15:36:32.384] [ERROR] ma-core - get All Basic Module :missing property NaN post 1234
[2022-01-10T15:36:32.386] [INFO] ma-core - get All Module success testing testing testing
[2022-01-10T15:36:32.387] [INFO] ma-core - get All Module success NaN post 1234
[2022-01-10T15:36:32.388] [ERROR] ma-core - get All Module :missing property testing testing testing
[2022-01-10T15:36:32.391] [ERROR] ma-core - get All Module :missing property NaN post 1234
[2022-01-10T15:36:32.395] [INFO] ma-core - get module By Id success testing testing testing
[2022-01-10T15:36:32.404] [INFO] ma-core - get module By Id success NaN post 1234
[2022-01-10T15:36:32.405] [ERROR] ma-core - get module By Id :module not found testing testing testing
[2022-01-10T15:36:32.407] [ERROR] ma-core - get module By Id :module not found testing testing testing
[2022-01-10T15:36:32.409] [ERROR] ma-core - get module By Id :module not found NaN post 1234
[2022-01-10T15:36:32.418] [INFO] ma-core - add Module success testing testing testing
[2022-01-10T15:36:32.421] [INFO] ma-core - add Module success NaN post 1234
[2022-01-10T15:36:32.422] [ERROR] ma-core - add Module :missing property testing testing testing
[2022-01-10T15:36:32.423] [ERROR] ma-core - add Module :missing property NaN post 1234
[2022-01-10T15:36:32.429] [INFO] ma-core - update module By Customer success testing testing testing
[2022-01-10T15:36:32.430] [INFO] ma-core - update module By Customer success NaN post 1234
[2022-01-10T15:36:32.432] [ERROR] ma-core - update module By Customer :module not found testing testing testing
[2022-01-10T15:36:32.433] [ERROR] ma-core - update module By Customer :module not found testing testing testing
[2022-01-10T15:36:32.436] [ERROR] ma-core - update module By Customer :module not found NaN post 1234
[2022-01-10T15:36:32.520] [INFO] ma-core - get All nomenclature success testing testing testing
[2022-01-10T15:36:32.522] [INFO] ma-core - get All nomenclature success testing testing testing
[2022-01-10T15:36:32.524] [INFO] ma-core - get All nomenclature success NaN post 1234
[2022-01-10T15:36:32.525] [ERROR] ma-core - get All nomenclature :get All nomenclature : testing testing testing
[2022-01-10T15:36:32.526] [ERROR] ma-core - get All nomenclature :get All nomenclature : NaN post 1234
[2022-01-10T15:36:32.554] [INFO] ma-core - delete Result Form success testing testing testing
[2022-01-10T15:36:32.556] [INFO] ma-core - delete Result Form success NaN post 1234
[2022-01-10T15:36:32.557] [ERROR] ma-core - delete Result Form :task not found testing testing testing
[2022-01-10T15:36:32.559] [ERROR] ma-core - delete Result Form :task not found NaN post 1234
[2022-01-10T15:36:32.571] [INFO] ma-core - get all result form success testing testing testing
[2022-01-10T15:36:32.573] [INFO] ma-core - get all result form success testing testing testing
[2022-01-10T15:36:32.574] [INFO] ma-core - get all result form success NaN post 1234
[2022-01-10T15:36:32.575] [ERROR] ma-core - get All result form :missing property testing testing testing
[2022-01-10T15:36:32.578] [ERROR] ma-core - get All result form :missing property NaN post 1234
[2022-01-10T15:36:32.582] [INFO] ma-core - get by id Result Form testing testing testing
[2022-01-10T15:36:32.585] [INFO] ma-core - get by id Result Form NaN post 1234
[2022-01-10T15:36:32.586] [ERROR] ma-core - get by id Result Form :task not found testing testing testing
[2022-01-10T15:36:32.588] [ERROR] ma-core - get by id Result Form :task not found NaN post 1234
[2022-01-10T15:36:32.594] [INFO] ma-core - add result form success testing testing testing
[2022-01-10T15:36:32.595] [INFO] ma-core - add result form success NaN post 1234
[2022-01-10T15:36:32.597] [ERROR] ma-core - add result form :missing property testing testing testing
[2022-01-10T15:36:32.599] [ERROR] ma-core - add result form :missing property NaN post 1234
[2022-01-10T15:36:32.604] [INFO] ma-core - update Result Form success testing testing testing
[2022-01-10T15:36:32.605] [INFO] ma-core - update Result Form success NaN post 1234
[2022-01-10T15:36:32.607] [ERROR] ma-core - update Result Form  :task not found testing testing testing
[2022-01-10T15:36:32.611] [ERROR] ma-core - update Result Form  :task not found NaN post 1234
[2022-01-10T15:36:32.619] [INFO] ma-core - delete Role success testing testing testing
[2022-01-10T15:36:32.620] [INFO] ma-core - delete Role success NaN post 1234
[2022-01-10T15:36:32.622] [ERROR] ma-core - delete Role :role not found testing testing testing
[2022-01-10T15:36:32.623] [ERROR] ma-core - delete Role :role not found NaN post 1234
[2022-01-10T15:36:32.625] [ERROR] ma-core - delete Role :missing ID testing testing testing
[2022-01-10T15:36:32.626] [ERROR] ma-core - delete Role :missing ID testing testing testing
[2022-01-10T15:36:32.634] [INFO] ma-core - get All Role success testing testing testing
[2022-01-10T15:36:32.636] [INFO] ma-core - get All Role success NaN post 1234
[2022-01-10T15:36:32.637] [ERROR] ma-core - get All Role :missing property testing testing testing
[2022-01-10T15:36:32.639] [ERROR] ma-core - get All Role :missing property NaN post 1234
[2022-01-10T15:36:32.643] [INFO] ma-core - get by id Role success testing testing testing
[2022-01-10T15:36:32.644] [INFO] ma-core - get by id Role success NaN post 1234
[2022-01-10T15:36:32.645] [ERROR] ma-core - get by id Role :role not found testing testing testing
[2022-01-10T15:36:32.647] [ERROR] ma-core - get by id Role :role not found testing testing testing
[2022-01-10T15:36:32.651] [ERROR] ma-core - get by id Role :role not found NaN post 1234
[2022-01-10T15:36:32.660] [INFO] ma-core - get by user Role success testing testing testing
[2022-01-10T15:36:32.661] [INFO] ma-core - get by user Role success NaN get 1234
[2022-01-10T15:36:32.666] [ERROR] ma-core - get by user Role :user not found testing testing testing
[2022-01-10T15:36:32.669] [ERROR] ma-core - get by user Role :role not found testing testing testing
[2022-01-10T15:36:32.671] [ERROR] ma-core - get by user Role :role not found NaN get 1234
[2022-01-10T15:36:32.673] [INFO] ma-core - add Role success testing testing testing
[2022-01-10T15:36:32.675] [ERROR] ma-core - add Role :missing property testing testing testing
[2022-01-10T15:36:32.676] [INFO] ma-core - add Role success NaN post 1234
[2022-01-10T15:36:32.677] [ERROR] ma-core - add Role :missing property NaN post 1234
[2022-01-10T15:36:32.688] [INFO] ma-core - update Role success testing testing testing
[2022-01-10T15:36:32.690] [INFO] ma-core - update Role success NaN post 1234
[2022-01-10T15:36:32.691] [ERROR] ma-core - update Role :role not found testing testing testing
[2022-01-10T15:36:32.693] [ERROR] ma-core - update Role :role not found testing testing testing
[2022-01-10T15:36:32.695] [ERROR] ma-core - update Role :role not found NaN post 1234
[2022-01-10T15:36:32.702] [INFO] ma-core - add Role History success testing testing testing
[2022-01-10T15:36:32.704] [INFO] ma-core - add Role History success NaN post 1234
[2022-01-10T15:36:32.705] [ERROR] ma-core - add Client :missing property testing testing testing
[2022-01-10T15:36:32.706] [ERROR] ma-core - add Client :missing property NaN post 1234
[2022-01-10T15:36:32.742] [ERROR] ma-core - 
[2022-01-10T15:36:32.758] [INFO] ma-core - Get all shifts success testing testing testing
[2022-01-10T15:36:32.778] [INFO] ma-core - Get all members success testing testing testing
[2022-01-10T15:36:32.802] [INFO] ma-core - delete sla success testing testing testing
[2022-01-10T15:36:32.804] [INFO] ma-core - delete sla success NaN post 1234
[2022-01-10T15:36:32.805] [ERROR] ma-core - delete Sla :sla not found testing testing testing
[2022-01-10T15:36:32.807] [ERROR] ma-core - delete Sla :sla not found testing testing testing
[2022-01-10T15:36:32.809] [ERROR] ma-core - delete Sla :sla not found NaN post 1234
[2022-01-10T15:36:32.819] [INFO] ma-core - get sla By Id success testing testing testing
[2022-01-10T15:36:32.821] [INFO] ma-core - get sla By Id success NaN post 1234
[2022-01-10T15:36:32.823] [ERROR] ma-core - get sla By Id :sla not found testing testing testing
[2022-01-10T15:36:32.825] [ERROR] ma-core - get sla By Id :sla not found testing testing testing
[2022-01-10T15:36:32.826] [ERROR] ma-core - get sla By Id :sla not found NaN post 1234
[2022-01-10T15:36:32.840] [ERROR] ma-core - Error occur while Getting Sla By slaContract Id : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/sla/getByslaContract/getslaBySlaContract.service.test.js:70:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:36:32.846] [INFO] ma-core - add Sla success testing testing testing
[2022-01-10T15:36:32.848] [INFO] ma-core - add Sla success NaN post 1234
[2022-01-10T15:36:32.851] [ERROR] ma-core - add Sla :missing property testing testing testing
[2022-01-10T15:36:32.854] [ERROR] ma-core - add Sla :missing property NaN post 1234
[2022-01-10T15:36:32.869] [INFO] ma-core - update sla By SlaContract success testing testing testing
[2022-01-10T15:36:32.870] [INFO] ma-core - update sla By SlaContract success NaN post 1234
[2022-01-10T15:36:32.872] [ERROR] ma-core - update sla By SlaContract :sla not found testing testing testing
[2022-01-10T15:36:32.873] [ERROR] ma-core - update sla By SlaContract :sla not found testing testing testing
[2022-01-10T15:36:32.875] [ERROR] ma-core - update sla By SlaContract :sla not found NaN post 1234
[2022-01-10T15:36:32.884] [INFO] ma-core - delete slaContract success testing testing testing
[2022-01-10T15:36:32.885] [INFO] ma-core - delete slaContract success NaN post 1234
[2022-01-10T15:36:32.887] [ERROR] ma-core - delete SlaContract :slaContract not found testing testing testing
[2022-01-10T15:36:32.888] [ERROR] ma-core - delete SlaContract :slaContract not found NaN post 1234
[2022-01-10T15:36:32.901] [ERROR] ma-core - Get by Customer Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/slaContract/getAllSlaContractByCustomerId/getAllSlaContractByCustomerIdServiceTest.js:78:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:36:32.903] [INFO] ma-core - get slaContract By Customer success testing testing testing
[2022-01-10T15:36:32.907] [INFO] ma-core - get slaContract By Customer success NaN post 1234
[2022-01-10T15:36:32.908] [ERROR] ma-core - get slaContract By Customer :customer not found testing testing testing
[2022-01-10T15:36:32.909] [ERROR] ma-core - get slaContract By Customer :customer not found NaN post 1234
[2022-01-10T15:36:32.911] [INFO] ma-core - get slaContract By Id success testing testing testing
[2022-01-10T15:36:32.913] [INFO] ma-core - get slaContract By Id success NaN post 1234
[2022-01-10T15:36:32.915] [ERROR] ma-core - get slaContract By Id :slaContract not found testing testing testing
[2022-01-10T15:36:32.917] [ERROR] ma-core - get slaContract By Id :slaContract not found NaN post 1234
[2022-01-10T15:36:32.923] [INFO] ma-core - add SlaContract success testing testing testing
[2022-01-10T15:36:32.924] [INFO] ma-core - add SlaContract success NaN post 1234
[2022-01-10T15:36:32.925] [ERROR] ma-core - add SlaContract :missing property testing testing testing
[2022-01-10T15:36:32.927] [ERROR] ma-core - add SlaContract :missing property NaN post 1234
[2022-01-10T15:36:32.936] [INFO] ma-core - update slaContract By Customer success testing testing testing
[2022-01-10T15:36:32.938] [INFO] ma-core - update slaContract By Customer success NaN post 1234
[2022-01-10T15:36:32.939] [ERROR] ma-core - update slaContract By Customer :slaContract not found testing testing testing
[2022-01-10T15:36:32.944] [ERROR] ma-core - update slaContract By Customer :slaContract not found NaN post 1234
[2022-01-10T15:36:33.057] [ERROR] ma-core - Get by Customer Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/system/getAllSystemByCustomerId/getAllSystemByCustomerIdServiceTest.js:52:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:36:33.080] [ERROR] ma-core - Get Categories by Customer ID and Type ID Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/system/getCategoryByTypesByCustomer/getCategoryByTypesByCustomerServiceTest.js:122:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:36:33.107] [ERROR] ma-core - Get types by Customer ID Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/system/getTypeByCustomer/getTypesByCustomerServiceTest.js:122:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:36:33.124] [INFO] ma-core - get All Task success testing testing testing
[2022-01-10T15:36:33.125] [INFO] ma-core - get All Task success NaN post 1234
[2022-01-10T15:36:33.129] [INFO] ma-core - get All Task By filter success testing testing testing
[2022-01-10T15:36:33.130] [ERROR] ma-core - get All Task By filter error :error testing testing testing
[2022-01-10T15:36:33.139] [INFO] ma-core - get All Task By filter success testing testing testing
[2022-01-10T15:36:33.142] [INFO] ma-core - get by id Task success testing testing testing
[2022-01-10T15:36:33.143] [INFO] ma-core - get by id Task success NaN post 1234
[2022-01-10T15:36:33.144] [ERROR] ma-core - get by id Task :task not found testing testing testing
[2022-01-10T15:36:33.145] [ERROR] ma-core - get by id Task :task not found NaN post 1234
[2022-01-10T15:36:33.152] [INFO] ma-core - get All Task By filter success testing testing testing
[2022-01-10T15:36:33.154] [ERROR] ma-core - get All Task By filter error :error testing testing testing
[2022-01-10T15:36:33.155] [INFO] ma-core - get All Task By filter success testing testing testing
[2022-01-10T15:36:33.211] [INFO] ma-core - get All Task By ID success testing testing testing
[2022-01-10T15:36:33.232] [INFO] ma-core - get All Task success testing testing testing
[2022-01-10T15:36:33.251] [INFO] ma-core - get Created Tasks success testing testing testing
[2022-01-10T15:36:33.255] [INFO] ma-core - get Created Tasks success NaN post 1234
[2022-01-10T15:36:33.265] [ERROR] ma-core - get Created Tasks error : error testing testing testing
[2022-01-10T15:36:33.270] [ERROR] ma-core - get Created Tasks error : error NaN post 1234
[2022-01-10T15:36:33.276] [INFO] ma-core - add Task success testing testing testing
[2022-01-10T15:36:33.278] [INFO] ma-core - add Task success NaN post 1234
[2022-01-10T15:36:33.279] [ERROR] ma-core - add Task :missing property testing testing testing
[2022-01-10T15:36:33.281] [ERROR] ma-core - add Task :missing property NaN post 1234
[2022-01-10T15:36:33.293] [INFO] ma-core - add Many Task success testing testing testing
[2022-01-10T15:36:33.296] [INFO] ma-core - add Many Task success NaN post 1234
[2022-01-10T15:36:33.298] [ERROR] ma-core - add Many Task :missing property testing testing testing
[2022-01-10T15:36:33.301] [ERROR] ma-core - add Many Task :missing property NaN post 1234
[2022-01-10T15:36:33.309] [INFO] ma-core - update Task success testing testing testing
[2022-01-10T15:36:33.310] [INFO] ma-core - update Task success NaN post 1234
[2022-01-10T15:36:33.311] [ERROR] ma-core - update Task :task not found testing testing testing
[2022-01-10T15:36:33.313] [ERROR] ma-core - update Task :task not found NaN post 1234
[2022-01-10T15:36:33.315] [DEBUG] ma-core - Before sending Info !!
[2022-01-10T15:36:33.315] [DEBUG] ma-core - Before sending inside the producer !
[2022-01-10T15:36:33.377] [INFO] ma-core - Update Task Assignee success testing testing testing
[2022-01-10T15:36:33.381] [INFO] ma-core - Update Task Assignee Incomplete testing testing testing
[2022-01-10T15:36:33.385] [ERROR] ma-core - Update Task Assignee :task not found testing testing testing
[2022-01-10T15:36:33.401] [INFO] ma-core - Canceled the Task testing testing testing
[2022-01-10T15:36:33.404] [INFO] ma-core - Canceled the Task NaN post 1234
[2022-01-10T15:36:33.410] [ERROR] ma-core - Failed to Cancel the Task :failed to update the task testing testing testing
[2022-01-10T15:36:33.412] [ERROR] ma-core - Failed to Cancel the Task :failed to update the task NaN post 1234
[2022-01-10T15:36:33.418] [INFO] ma-core - Closed the Task testing testing testing
[2022-01-10T15:36:33.421] [INFO] ma-core - Closed the Task NaN post 1234
[2022-01-10T15:36:33.425] [ERROR] ma-core - Failed to reject the Task :failed to update the task testing testing testing
[2022-01-10T15:36:33.427] [ERROR] ma-core - Failed to reject the Task :failed to update the task NaN post 1234
[2022-01-10T15:36:33.429] [INFO] ma-core - Deleted the Task testing testing testing
[2022-01-10T15:36:33.431] [INFO] ma-core - Deleted the Task NaN post 1234
[2022-01-10T15:36:33.436] [ERROR] ma-core - Failed to delete the Task :failed to update the task testing testing testing
[2022-01-10T15:36:33.438] [ERROR] ma-core - Failed to delete the Task :failed to update the task NaN post 1234
[2022-01-10T15:36:33.440] [INFO] ma-core - Finished the Task testing testing testing
[2022-01-10T15:36:33.441] [INFO] ma-core - Finished the Task NaN post 1234
[2022-01-10T15:36:33.446] [ERROR] ma-core - Failed to finish the Task :failed to update the task testing testing testing
[2022-01-10T15:36:33.450] [ERROR] ma-core - Failed to finish the Task :failed to update the task NaN post 1234
[2022-01-10T15:36:33.453] [INFO] ma-core - Rejected the Task testing testing testing
[2022-01-10T15:36:33.455] [INFO] ma-core - Rejected the Task NaN post 1234
[2022-01-10T15:36:33.459] [ERROR] ma-core - Failed to reject the Task :failed to update the task testing testing testing
[2022-01-10T15:36:33.460] [ERROR] ma-core - Failed to reject the Task :failed to update the task NaN post 1234
[2022-01-10T15:36:33.465] [ERROR] ma-core - An unexpected error occurred during auto start task Error: WARNING: Date in past. Will never be fired.
    at CronTime.sendAt (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:148:12)
    at CronTime.getTimeout (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:175:29)
    at CronJob.start (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:613:31)
    at new CronJob (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:576:10)
    at module.exports (/home/azer/avaxia-monitpring-app/core-service/services/task/autoStartTaskCron.js:2:1041)
    at Object.exports.validateTask (/home/azer/avaxia-monitpring-app/core-service/controllers/task.controller.js:11:699)
    at async Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/task/updateState/validateTask.controller.test.js:51:5)
[2022-01-10T15:36:33.466] [INFO] ma-core - Validated the Task testing testing testing
[2022-01-10T15:36:33.470] [ERROR] ma-core - An unexpected error occurred during auto start task Error: WARNING: Date in past. Will never be fired.
    at CronTime.sendAt (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:148:12)
    at CronTime.getTimeout (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:175:29)
    at CronJob.start (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:613:31)
    at new CronJob (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:576:10)
    at module.exports (/home/azer/avaxia-monitpring-app/core-service/services/task/autoStartTaskCron.js:2:1041)
    at Object.exports.validateTask (/home/azer/avaxia-monitpring-app/core-service/controllers/task.controller.js:11:699)
    at async Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/task/updateState/validateTask.controller.test.js:95:5)
[2022-01-10T15:36:33.470] [INFO] ma-core - Validated the Task NaN post 1234
[2022-01-10T15:36:33.477] [ERROR] ma-core - An unexpected error occurred during auto start task Error: WARNING: Date in past. Will never be fired.
    at CronTime.sendAt (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:148:12)
    at CronTime.getTimeout (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:175:29)
    at CronJob.start (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:613:31)
    at new CronJob (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:576:10)
    at module.exports (/home/azer/avaxia-monitpring-app/core-service/services/task/autoStartTaskCron.js:2:1041)
    at Object.exports.validateTask (/home/azer/avaxia-monitpring-app/core-service/controllers/task.controller.js:11:699)
    at async Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/task/updateState/validateTask.controller.test.js:176:5)
[2022-01-10T15:36:33.478] [ERROR] ma-core - Failed to validate the Task :failed to update the task testing testing testing
[2022-01-10T15:36:33.485] [ERROR] ma-core - An unexpected error occurred during auto start task Error: WARNING: Date in past. Will never be fired.
    at CronTime.sendAt (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:148:12)
    at CronTime.getTimeout (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:175:29)
    at CronJob.start (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:613:31)
    at new CronJob (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:576:10)
    at module.exports (/home/azer/avaxia-monitpring-app/core-service/services/task/autoStartTaskCron.js:2:1041)
    at Object.exports.validateTask (/home/azer/avaxia-monitpring-app/core-service/controllers/task.controller.js:11:699)
    at async Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/task/updateState/validateTask.controller.test.js:219:5)
[2022-01-10T15:36:33.486] [ERROR] ma-core - Failed to validate the Task :failed to update the task NaN post 1234
[2022-01-10T15:36:33.494] [INFO] ma-core - update Task success testing testing testing
[2022-01-10T15:36:33.505] [INFO] ma-core - update Task success NaN post 1234
[2022-01-10T15:36:33.509] [ERROR] ma-core - update Task :You are not authorized to perform this action testing testing testing
[2022-01-10T15:36:33.512] [ERROR] ma-core - update Task :task not found NaN post 1234
[2022-01-10T15:36:33.587] [ERROR] ma-core - random Error
[2022-01-10T15:36:34.293] [ERROR] ma-core - random error
[2022-01-10T15:37:28.468] [INFO] ma-core - database URI mongodb://localhost:27017/core
[2022-01-10T15:37:29.551] [INFO] ma-core - server started at port 5000
[2022-01-10T15:37:29.578] [INFO] ma-core - mongodb conected
[2022-01-10T15:37:29.663] [INFO] ma-core - add Client success testing testing testing
[2022-01-10T15:37:29.665] [ERROR] ma-core - add Client :missing property testing testing testing
[2022-01-10T15:37:29.668] [ERROR] ma-core - add Client :missing property NaN post 1234
[2022-01-10T15:37:29.681] [ERROR] ma-core - Delete Error : Error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/client/delete/deleteClient.service.test.js:62:33)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:37:29.683] [ERROR] ma-core - Delete Error : Error: random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/client/delete/deleteClient.service.test.js:72:33)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:37:29.709] [ERROR] ma-core - Get by System Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/client/getClientsBySystemId/getAllBySystemServiceTest.js:49:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:37:29.717] [ERROR] ma-core - Error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/client/update/updateClient.service.test.js:70:33)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:37:29.730] [INFO] ma-core - get all Customer success testing testing testing
[2022-01-10T15:37:29.732] [INFO] ma-core - get all Customer success NaN post 1234
[2022-01-10T15:37:29.733] [INFO] ma-core - get all Customer success testing testing testing
[2022-01-10T15:37:29.734] [INFO] ma-core - get all Customer error testing testing testing
[2022-01-10T15:37:29.736] [INFO] ma-core - get all Customer error NaN post 1234
[2022-01-10T15:37:29.750] [INFO] ma-core - get Customer error testing testing testing
[2022-01-10T15:37:29.757] [ERROR] ma-core - Error: random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/customer/getById/getByIdCustomer.service.test.js:88:24)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:37:29.771] [INFO] ma-core - add customer success testing testing testing
[2022-01-10T15:37:29.773] [ERROR] ma-core - add customer fail :missing property testing testing testing
[2022-01-10T15:37:29.915] [ERROR] ma-core - Delete Error : Error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/host/delete/deleteHost.service.test.js:72:33)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:37:29.923] [ERROR] ma-core - Get by System Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/host/getAllBySystem/getAllBySystemServiceTest.js:49:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:37:29.931] [ERROR] ma-core - Get by ID Error : Error: random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/host/getById/getByIdHost.service.test.js:58:24)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:37:29.938] [ERROR] ma-core - expected findOneAndUpdate to have been called exactly once, but it was called 0 times
[2022-01-10T15:37:29.949] [ERROR] ma-core - Update Error : Error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/host/update/updateHost.service.test.js:79:33)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:37:27.486] [INFO] ma-core - cancel itOperation success testing testing testing
[2022-01-10T15:37:27.486] [ERROR] ma-core - cancel ItOperation :itOperation not found testing testing testing
[2022-01-10T15:37:27.489] [INFO] ma-core - finish itOperation success testing testing testing
[2022-01-10T15:37:27.489] [ERROR] ma-core - finish ItOperation :itOperation not found testing testing testing
[2022-01-10T15:37:29.961] [INFO] ma-core - get All Active itOperation success testing testing testing
[2022-01-10T15:37:29.966] [INFO] ma-core - get All Archived itOperation success testing testing testing
[2022-01-10T15:37:29.974] [ERROR] ma-core - Error occur while Getting ItOperation By System Id : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/itOperation/getAllBySystem/getAllBySystemServiceTest.js:50:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:37:29.984] [INFO] ma-core - add ItOperation success testing testing testing
[2022-01-10T15:37:29.985] [ERROR] ma-core - add ItOperation fail :missing property testing testing testing
[2022-01-10T15:37:27.508] [INFO] ma-core - remind itOperation success testing testing testing
[2022-01-10T15:37:27.508] [ERROR] ma-core - remind ItOperation :itOperation not found testing testing testing
[2022-01-10T15:37:27.510] [INFO] ma-core - send changes itOperation success testing testing testing
[2022-01-10T15:37:27.510] [ERROR] ma-core - send changes ItOperation :itOperation not found testing testing testing
[2022-01-10T15:37:30.000] [INFO] ma-core - update itOperation success testing testing testing
[2022-01-10T15:37:30.002] [ERROR] ma-core - update ItOperation :itOperation not found testing testing testing
[2022-01-10T15:37:30.029] [INFO] ma-core - delete licence success testing testing testing
[2022-01-10T15:37:30.031] [INFO] ma-core - delete licence success NaN post 1234
[2022-01-10T15:37:30.032] [ERROR] ma-core - delete Licence :licence not found testing testing testing
[2022-01-10T15:37:30.033] [ERROR] ma-core - delete Licence :licence not found NaN post 1234
[2022-01-10T15:37:30.041] [INFO] ma-core - get latest customer licence By Id success testing testing testing
[2022-01-10T15:37:30.045] [INFO] ma-core - get latest customer licence By Id success NaN post 1234
[2022-01-10T15:37:30.047] [ERROR] ma-core - get licence By Id :Missing Customer ID NaN post 1234
[2022-01-10T15:37:30.048] [ERROR] ma-core - get licence By Id :Missing Customer ID testing testing testing
[2022-01-10T15:37:30.049] [ERROR] ma-core - get licence By Id :licence not found testing testing testing
[2022-01-10T15:37:30.051] [ERROR] ma-core - get licence By Id :licence not found NaN post 1234
[2022-01-10T15:37:30.054] [ERROR] ma-core - Error occur while Getting Licence By Customer Id : Error: random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/licence/getActiveLicence/getActiveLIcenceServiceTest.js:52:17)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:37:30.059] [ERROR] ma-core - Error occur while Getting Licence By Customer Id : Error: random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/licence/getByCustomer/getByCustomerLicence.service.test.js:61:17)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:37:30.063] [INFO] ma-core - get licence By Id success testing testing testing
[2022-01-10T15:37:30.065] [INFO] ma-core - get licence By Id success NaN post 1234
[2022-01-10T15:37:30.066] [ERROR] ma-core - get licence By Id :licence not found testing testing testing
[2022-01-10T15:37:30.067] [ERROR] ma-core - get licence By Id :licence not found NaN post 1234
[2022-01-10T15:37:30.078] [INFO] ma-core - add Licence success testing testing testing
[2022-01-10T15:37:30.080] [INFO] ma-core - add Licence success NaN post 1234
[2022-01-10T15:37:30.081] [ERROR] ma-core - add Licence :missing property testing testing testing
[2022-01-10T15:37:30.083] [ERROR] ma-core - add Licence :missing property NaN post 1234
[2022-01-10T15:37:30.093] [INFO] ma-core - update licence By Customer success testing testing testing
[2022-01-10T15:37:30.094] [INFO] ma-core - update licence By Customer success NaN post 1234
[2022-01-10T15:37:30.096] [ERROR] ma-core - update licence By Customer :licence not found testing testing testing
[2022-01-10T15:37:30.097] [ERROR] ma-core - update licence By Customer :licence not found NaN post 1234
[2022-01-10T15:37:30.117] [ERROR] ma-core - delete Map By Id :MAP not found testing testing testing
[2022-01-10T15:37:30.119] [ERROR] ma-core - delete Map By Id :missing ID testing testing testing
[2022-01-10T15:37:30.121] [ERROR] ma-core - delete Map By Id :missing ID testing testing testing
[2022-01-10T15:37:30.125] [ERROR] ma-core - delete Map By Id :missing ID NaN post 1234
[2022-01-10T15:37:30.144] [ERROR] ma-core - Get by System Error : TypeError: moment(...).tz(...).format is not a function
    at /home/azer/avaxia-monitpring-app/core-service/services/map/getBySystemId.js:2:1950
    at Array.map (<anonymous>)
    at module.exports (/home/azer/avaxia-monitpring-app/core-service/services/map/getBySystemId.js:2:1771)
    at async Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/map/getAllBySystem/getAllBySystemServiceTest.js:71:17)
[2022-01-10T15:37:30.151] [ERROR] ma-core - Get by System Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/map/getAllBySystem/getAllBySystemServiceTest.js:98:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:37:30.179] [INFO] ma-core - delete module success testing testing testing
[2022-01-10T15:37:30.181] [INFO] ma-core - delete module success NaN post 1234
[2022-01-10T15:37:30.182] [ERROR] ma-core - delete Module :module not found testing testing testing
[2022-01-10T15:37:30.183] [ERROR] ma-core - delete Module :module not found NaN post 1234
[2022-01-10T15:37:30.185] [ERROR] ma-core - delete Module :missing ID testing testing testing
[2022-01-10T15:37:30.187] [ERROR] ma-core - delete Module :missing ID testing testing testing
[2022-01-10T15:37:30.193] [INFO] ma-core - get All Basic Module success testing testing testing
[2022-01-10T15:37:30.194] [INFO] ma-core - get All Basic Module success NaN post 1234
[2022-01-10T15:37:30.197] [ERROR] ma-core - get All Basic Module :missing property testing testing testing
[2022-01-10T15:37:30.198] [ERROR] ma-core - get All Basic Module :missing property NaN post 1234
[2022-01-10T15:37:30.200] [INFO] ma-core - get All Module success testing testing testing
[2022-01-10T15:37:30.201] [INFO] ma-core - get All Module success NaN post 1234
[2022-01-10T15:37:30.202] [ERROR] ma-core - get All Module :missing property testing testing testing
[2022-01-10T15:37:30.205] [ERROR] ma-core - get All Module :missing property NaN post 1234
[2022-01-10T15:37:30.211] [INFO] ma-core - get module By Id success testing testing testing
[2022-01-10T15:37:30.212] [INFO] ma-core - get module By Id success NaN post 1234
[2022-01-10T15:37:30.213] [ERROR] ma-core - get module By Id :module not found testing testing testing
[2022-01-10T15:37:30.215] [ERROR] ma-core - get module By Id :module not found testing testing testing
[2022-01-10T15:37:30.217] [ERROR] ma-core - get module By Id :module not found NaN post 1234
[2022-01-10T15:37:30.226] [INFO] ma-core - add Module success testing testing testing
[2022-01-10T15:37:30.228] [INFO] ma-core - add Module success NaN post 1234
[2022-01-10T15:37:30.230] [ERROR] ma-core - add Module :missing property testing testing testing
[2022-01-10T15:37:30.231] [ERROR] ma-core - add Module :missing property NaN post 1234
[2022-01-10T15:37:30.236] [INFO] ma-core - update module By Customer success testing testing testing
[2022-01-10T15:37:30.237] [INFO] ma-core - update module By Customer success NaN post 1234
[2022-01-10T15:37:30.239] [ERROR] ma-core - update module By Customer :module not found testing testing testing
[2022-01-10T15:37:30.241] [ERROR] ma-core - update module By Customer :module not found testing testing testing
[2022-01-10T15:37:30.244] [ERROR] ma-core - update module By Customer :module not found NaN post 1234
[2022-01-10T15:37:30.319] [INFO] ma-core - get All nomenclature success testing testing testing
[2022-01-10T15:37:30.321] [INFO] ma-core - get All nomenclature success testing testing testing
[2022-01-10T15:37:30.324] [INFO] ma-core - get All nomenclature success NaN post 1234
[2022-01-10T15:37:30.325] [ERROR] ma-core - get All nomenclature :get All nomenclature : testing testing testing
[2022-01-10T15:37:30.327] [ERROR] ma-core - get All nomenclature :get All nomenclature : NaN post 1234
[2022-01-10T15:37:30.358] [INFO] ma-core - delete Result Form success testing testing testing
[2022-01-10T15:37:30.359] [INFO] ma-core - delete Result Form success NaN post 1234
[2022-01-10T15:37:30.361] [ERROR] ma-core - delete Result Form :task not found testing testing testing
[2022-01-10T15:37:30.362] [ERROR] ma-core - delete Result Form :task not found NaN post 1234
[2022-01-10T15:37:30.373] [INFO] ma-core - get all result form success testing testing testing
[2022-01-10T15:37:30.375] [INFO] ma-core - get all result form success testing testing testing
[2022-01-10T15:37:30.377] [INFO] ma-core - get all result form success NaN post 1234
[2022-01-10T15:37:30.379] [ERROR] ma-core - get All result form :missing property testing testing testing
[2022-01-10T15:37:30.381] [ERROR] ma-core - get All result form :missing property NaN post 1234
[2022-01-10T15:37:30.384] [INFO] ma-core - get by id Result Form testing testing testing
[2022-01-10T15:37:30.386] [INFO] ma-core - get by id Result Form NaN post 1234
[2022-01-10T15:37:30.388] [ERROR] ma-core - get by id Result Form :task not found testing testing testing
[2022-01-10T15:37:30.391] [ERROR] ma-core - get by id Result Form :task not found NaN post 1234
[2022-01-10T15:37:30.397] [INFO] ma-core - add result form success testing testing testing
[2022-01-10T15:37:30.398] [INFO] ma-core - add result form success NaN post 1234
[2022-01-10T15:37:30.400] [ERROR] ma-core - add result form :missing property testing testing testing
[2022-01-10T15:37:30.401] [ERROR] ma-core - add result form :missing property NaN post 1234
[2022-01-10T15:37:30.406] [INFO] ma-core - update Result Form success testing testing testing
[2022-01-10T15:37:30.407] [INFO] ma-core - update Result Form success NaN post 1234
[2022-01-10T15:37:30.409] [ERROR] ma-core - update Result Form  :task not found testing testing testing
[2022-01-10T15:37:30.410] [ERROR] ma-core - update Result Form  :task not found NaN post 1234
[2022-01-10T15:37:30.417] [INFO] ma-core - delete Role success testing testing testing
[2022-01-10T15:37:30.418] [INFO] ma-core - delete Role success NaN post 1234
[2022-01-10T15:37:30.419] [ERROR] ma-core - delete Role :role not found testing testing testing
[2022-01-10T15:37:30.421] [ERROR] ma-core - delete Role :role not found NaN post 1234
[2022-01-10T15:37:30.423] [ERROR] ma-core - delete Role :missing ID testing testing testing
[2022-01-10T15:37:30.425] [ERROR] ma-core - delete Role :missing ID testing testing testing
[2022-01-10T15:37:30.432] [INFO] ma-core - get All Role success testing testing testing
[2022-01-10T15:37:30.433] [INFO] ma-core - get All Role success NaN post 1234
[2022-01-10T15:37:30.434] [ERROR] ma-core - get All Role :missing property testing testing testing
[2022-01-10T15:37:30.437] [ERROR] ma-core - get All Role :missing property NaN post 1234
[2022-01-10T15:37:30.441] [INFO] ma-core - get by id Role success testing testing testing
[2022-01-10T15:37:30.443] [INFO] ma-core - get by id Role success NaN post 1234
[2022-01-10T15:37:30.444] [ERROR] ma-core - get by id Role :role not found testing testing testing
[2022-01-10T15:37:30.446] [ERROR] ma-core - get by id Role :role not found testing testing testing
[2022-01-10T15:37:30.454] [ERROR] ma-core - get by id Role :role not found NaN post 1234
[2022-01-10T15:37:30.463] [INFO] ma-core - get by user Role success testing testing testing
[2022-01-10T15:37:30.465] [INFO] ma-core - get by user Role success NaN get 1234
[2022-01-10T15:37:30.468] [ERROR] ma-core - get by user Role :user not found testing testing testing
[2022-01-10T15:37:30.469] [ERROR] ma-core - get by user Role :role not found testing testing testing
[2022-01-10T15:37:30.472] [ERROR] ma-core - get by user Role :role not found NaN get 1234
[2022-01-10T15:37:30.474] [INFO] ma-core - add Role success testing testing testing
[2022-01-10T15:37:30.476] [ERROR] ma-core - add Role :missing property testing testing testing
[2022-01-10T15:37:30.478] [INFO] ma-core - add Role success NaN post 1234
[2022-01-10T15:37:30.479] [ERROR] ma-core - add Role :missing property NaN post 1234
[2022-01-10T15:37:30.491] [INFO] ma-core - update Role success testing testing testing
[2022-01-10T15:37:30.493] [INFO] ma-core - update Role success NaN post 1234
[2022-01-10T15:37:30.495] [ERROR] ma-core - update Role :role not found testing testing testing
[2022-01-10T15:37:30.497] [ERROR] ma-core - update Role :role not found testing testing testing
[2022-01-10T15:37:30.499] [ERROR] ma-core - update Role :role not found NaN post 1234
[2022-01-10T15:37:30.506] [INFO] ma-core - add Role History success testing testing testing
[2022-01-10T15:37:30.508] [INFO] ma-core - add Role History success NaN post 1234
[2022-01-10T15:37:30.510] [ERROR] ma-core - add Client :missing property testing testing testing
[2022-01-10T15:37:30.511] [ERROR] ma-core - add Client :missing property NaN post 1234
[2022-01-10T15:37:30.538] [ERROR] ma-core - 
[2022-01-10T15:37:30.554] [INFO] ma-core - Get all shifts success testing testing testing
[2022-01-10T15:37:30.580] [INFO] ma-core - Get all members success testing testing testing
[2022-01-10T15:37:30.601] [INFO] ma-core - delete sla success testing testing testing
[2022-01-10T15:37:30.602] [INFO] ma-core - delete sla success NaN post 1234
[2022-01-10T15:37:30.604] [ERROR] ma-core - delete Sla :sla not found testing testing testing
[2022-01-10T15:37:30.606] [ERROR] ma-core - delete Sla :sla not found testing testing testing
[2022-01-10T15:37:30.609] [ERROR] ma-core - delete Sla :sla not found NaN post 1234
[2022-01-10T15:37:30.616] [INFO] ma-core - get sla By Id success testing testing testing
[2022-01-10T15:37:30.618] [INFO] ma-core - get sla By Id success NaN post 1234
[2022-01-10T15:37:30.619] [ERROR] ma-core - get sla By Id :sla not found testing testing testing
[2022-01-10T15:37:30.622] [ERROR] ma-core - get sla By Id :sla not found testing testing testing
[2022-01-10T15:37:30.624] [ERROR] ma-core - get sla By Id :sla not found NaN post 1234
[2022-01-10T15:37:30.631] [ERROR] ma-core - Error occur while Getting Sla By slaContract Id : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/sla/getByslaContract/getslaBySlaContract.service.test.js:70:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:37:30.639] [INFO] ma-core - add Sla success testing testing testing
[2022-01-10T15:37:30.642] [INFO] ma-core - add Sla success NaN post 1234
[2022-01-10T15:37:30.643] [ERROR] ma-core - add Sla :missing property testing testing testing
[2022-01-10T15:37:30.645] [ERROR] ma-core - add Sla :missing property NaN post 1234
[2022-01-10T15:37:30.660] [INFO] ma-core - update sla By SlaContract success testing testing testing
[2022-01-10T15:37:30.662] [INFO] ma-core - update sla By SlaContract success NaN post 1234
[2022-01-10T15:37:30.663] [ERROR] ma-core - update sla By SlaContract :sla not found testing testing testing
[2022-01-10T15:37:30.665] [ERROR] ma-core - update sla By SlaContract :sla not found testing testing testing
[2022-01-10T15:37:30.666] [ERROR] ma-core - update sla By SlaContract :sla not found NaN post 1234
[2022-01-10T15:37:30.679] [INFO] ma-core - delete slaContract success testing testing testing
[2022-01-10T15:37:30.681] [INFO] ma-core - delete slaContract success NaN post 1234
[2022-01-10T15:37:30.682] [ERROR] ma-core - delete SlaContract :slaContract not found testing testing testing
[2022-01-10T15:37:30.684] [ERROR] ma-core - delete SlaContract :slaContract not found NaN post 1234
[2022-01-10T15:37:30.696] [ERROR] ma-core - Get by Customer Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/slaContract/getAllSlaContractByCustomerId/getAllSlaContractByCustomerIdServiceTest.js:78:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:37:30.698] [INFO] ma-core - get slaContract By Customer success testing testing testing
[2022-01-10T15:37:30.702] [INFO] ma-core - get slaContract By Customer success NaN post 1234
[2022-01-10T15:37:30.703] [ERROR] ma-core - get slaContract By Customer :customer not found testing testing testing
[2022-01-10T15:37:30.705] [ERROR] ma-core - get slaContract By Customer :customer not found NaN post 1234
[2022-01-10T15:37:30.707] [INFO] ma-core - get slaContract By Id success testing testing testing
[2022-01-10T15:37:30.709] [INFO] ma-core - get slaContract By Id success NaN post 1234
[2022-01-10T15:37:30.710] [ERROR] ma-core - get slaContract By Id :slaContract not found testing testing testing
[2022-01-10T15:37:30.712] [ERROR] ma-core - get slaContract By Id :slaContract not found NaN post 1234
[2022-01-10T15:37:30.717] [INFO] ma-core - add SlaContract success testing testing testing
[2022-01-10T15:37:30.718] [INFO] ma-core - add SlaContract success NaN post 1234
[2022-01-10T15:37:30.720] [ERROR] ma-core - add SlaContract :missing property testing testing testing
[2022-01-10T15:37:30.721] [ERROR] ma-core - add SlaContract :missing property NaN post 1234
[2022-01-10T15:37:30.730] [INFO] ma-core - update slaContract By Customer success testing testing testing
[2022-01-10T15:37:30.732] [INFO] ma-core - update slaContract By Customer success NaN post 1234
[2022-01-10T15:37:30.733] [ERROR] ma-core - update slaContract By Customer :slaContract not found testing testing testing
[2022-01-10T15:37:30.735] [ERROR] ma-core - update slaContract By Customer :slaContract not found NaN post 1234
[2022-01-10T15:37:30.841] [ERROR] ma-core - Get by Customer Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/system/getAllSystemByCustomerId/getAllSystemByCustomerIdServiceTest.js:52:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:37:30.867] [ERROR] ma-core - Get Categories by Customer ID and Type ID Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/system/getCategoryByTypesByCustomer/getCategoryByTypesByCustomerServiceTest.js:122:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:37:30.896] [ERROR] ma-core - Get types by Customer ID Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/system/getTypeByCustomer/getTypesByCustomerServiceTest.js:122:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:37:30.913] [INFO] ma-core - get All Task success testing testing testing
[2022-01-10T15:37:30.914] [INFO] ma-core - get All Task success NaN post 1234
[2022-01-10T15:37:30.918] [INFO] ma-core - get All Task By filter success testing testing testing
[2022-01-10T15:37:30.919] [ERROR] ma-core - get All Task By filter error :error testing testing testing
[2022-01-10T15:37:30.920] [INFO] ma-core - get All Task By filter success testing testing testing
[2022-01-10T15:37:30.922] [INFO] ma-core - get by id Task success testing testing testing
[2022-01-10T15:37:30.925] [INFO] ma-core - get by id Task success NaN post 1234
[2022-01-10T15:37:30.927] [ERROR] ma-core - get by id Task :task not found testing testing testing
[2022-01-10T15:37:30.928] [ERROR] ma-core - get by id Task :task not found NaN post 1234
[2022-01-10T15:37:30.933] [INFO] ma-core - get All Task By filter success testing testing testing
[2022-01-10T15:37:30.934] [ERROR] ma-core - get All Task By filter error :error testing testing testing
[2022-01-10T15:37:30.936] [INFO] ma-core - get All Task By filter success testing testing testing
[2022-01-10T15:37:31.002] [INFO] ma-core - get All Task By ID success testing testing testing
[2022-01-10T15:37:31.023] [INFO] ma-core - get All Task success testing testing testing
[2022-01-10T15:37:31.042] [INFO] ma-core - get Created Tasks success testing testing testing
[2022-01-10T15:37:31.047] [INFO] ma-core - get Created Tasks success NaN post 1234
[2022-01-10T15:37:31.052] [ERROR] ma-core - get Created Tasks error : error testing testing testing
[2022-01-10T15:37:31.057] [ERROR] ma-core - get Created Tasks error : error NaN post 1234
[2022-01-10T15:37:31.063] [INFO] ma-core - add Task success testing testing testing
[2022-01-10T15:37:31.067] [INFO] ma-core - add Task success NaN post 1234
[2022-01-10T15:37:31.068] [ERROR] ma-core - add Task :missing property testing testing testing
[2022-01-10T15:37:31.070] [ERROR] ma-core - add Task :missing property NaN post 1234
[2022-01-10T15:37:31.083] [INFO] ma-core - add Many Task success testing testing testing
[2022-01-10T15:37:31.086] [INFO] ma-core - add Many Task success NaN post 1234
[2022-01-10T15:37:31.088] [ERROR] ma-core - add Many Task :missing property testing testing testing
[2022-01-10T15:37:31.090] [ERROR] ma-core - add Many Task :missing property NaN post 1234
[2022-01-10T15:37:31.099] [INFO] ma-core - update Task success testing testing testing
[2022-01-10T15:37:31.100] [INFO] ma-core - update Task success NaN post 1234
[2022-01-10T15:37:31.102] [ERROR] ma-core - update Task :task not found testing testing testing
[2022-01-10T15:37:31.103] [ERROR] ma-core - update Task :task not found NaN post 1234
[2022-01-10T15:37:31.105] [DEBUG] ma-core - Before sending Info !!
[2022-01-10T15:37:31.105] [DEBUG] ma-core - Before sending inside the producer !
[2022-01-10T15:37:31.168] [INFO] ma-core - Update Task Assignee success testing testing testing
[2022-01-10T15:37:31.170] [INFO] ma-core - Update Task Assignee Incomplete testing testing testing
[2022-01-10T15:37:31.171] [ERROR] ma-core - Update Task Assignee :task not found testing testing testing
[2022-01-10T15:37:31.181] [INFO] ma-core - Canceled the Task testing testing testing
[2022-01-10T15:37:31.183] [INFO] ma-core - Canceled the Task NaN post 1234
[2022-01-10T15:37:31.187] [ERROR] ma-core - Failed to Cancel the Task :failed to update the task testing testing testing
[2022-01-10T15:37:31.189] [ERROR] ma-core - Failed to Cancel the Task :failed to update the task NaN post 1234
[2022-01-10T15:37:31.191] [INFO] ma-core - Closed the Task testing testing testing
[2022-01-10T15:37:31.193] [INFO] ma-core - Closed the Task NaN post 1234
[2022-01-10T15:37:31.197] [ERROR] ma-core - Failed to reject the Task :failed to update the task testing testing testing
[2022-01-10T15:37:31.199] [ERROR] ma-core - Failed to reject the Task :failed to update the task NaN post 1234
[2022-01-10T15:37:31.201] [INFO] ma-core - Deleted the Task testing testing testing
[2022-01-10T15:37:31.202] [INFO] ma-core - Deleted the Task NaN post 1234
[2022-01-10T15:37:31.207] [ERROR] ma-core - Failed to delete the Task :failed to update the task testing testing testing
[2022-01-10T15:37:31.209] [ERROR] ma-core - Failed to delete the Task :failed to update the task NaN post 1234
[2022-01-10T15:37:31.211] [INFO] ma-core - Finished the Task testing testing testing
[2022-01-10T15:37:31.213] [INFO] ma-core - Finished the Task NaN post 1234
[2022-01-10T15:37:31.217] [ERROR] ma-core - Failed to finish the Task :failed to update the task testing testing testing
[2022-01-10T15:37:31.218] [ERROR] ma-core - Failed to finish the Task :failed to update the task NaN post 1234
[2022-01-10T15:37:31.220] [INFO] ma-core - Rejected the Task testing testing testing
[2022-01-10T15:37:31.222] [INFO] ma-core - Rejected the Task NaN post 1234
[2022-01-10T15:37:31.226] [ERROR] ma-core - Failed to reject the Task :failed to update the task testing testing testing
[2022-01-10T15:37:31.228] [ERROR] ma-core - Failed to reject the Task :failed to update the task NaN post 1234
[2022-01-10T15:37:31.231] [ERROR] ma-core - An unexpected error occurred during auto start task Error: WARNING: Date in past. Will never be fired.
    at CronTime.sendAt (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:148:12)
    at CronTime.getTimeout (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:175:29)
    at CronJob.start (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:613:31)
    at new CronJob (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:576:10)
    at module.exports (/home/azer/avaxia-monitpring-app/core-service/services/task/autoStartTaskCron.js:2:1041)
    at Object.exports.validateTask (/home/azer/avaxia-monitpring-app/core-service/controllers/task.controller.js:11:699)
    at async Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/task/updateState/validateTask.controller.test.js:51:5)
[2022-01-10T15:37:31.232] [INFO] ma-core - Validated the Task testing testing testing
[2022-01-10T15:37:31.235] [ERROR] ma-core - An unexpected error occurred during auto start task Error: WARNING: Date in past. Will never be fired.
    at CronTime.sendAt (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:148:12)
    at CronTime.getTimeout (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:175:29)
    at CronJob.start (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:613:31)
    at new CronJob (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:576:10)
    at module.exports (/home/azer/avaxia-monitpring-app/core-service/services/task/autoStartTaskCron.js:2:1041)
    at Object.exports.validateTask (/home/azer/avaxia-monitpring-app/core-service/controllers/task.controller.js:11:699)
    at async Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/task/updateState/validateTask.controller.test.js:95:5)
[2022-01-10T15:37:31.235] [INFO] ma-core - Validated the Task NaN post 1234
[2022-01-10T15:37:31.244] [ERROR] ma-core - An unexpected error occurred during auto start task Error: WARNING: Date in past. Will never be fired.
    at CronTime.sendAt (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:148:12)
    at CronTime.getTimeout (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:175:29)
    at CronJob.start (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:613:31)
    at new CronJob (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:576:10)
    at module.exports (/home/azer/avaxia-monitpring-app/core-service/services/task/autoStartTaskCron.js:2:1041)
    at Object.exports.validateTask (/home/azer/avaxia-monitpring-app/core-service/controllers/task.controller.js:11:699)
    at async Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/task/updateState/validateTask.controller.test.js:176:5)
[2022-01-10T15:37:31.244] [ERROR] ma-core - Failed to validate the Task :failed to update the task testing testing testing
[2022-01-10T15:37:31.247] [ERROR] ma-core - An unexpected error occurred during auto start task Error: WARNING: Date in past. Will never be fired.
    at CronTime.sendAt (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:148:12)
    at CronTime.getTimeout (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:175:29)
    at CronJob.start (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:613:31)
    at new CronJob (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:576:10)
    at module.exports (/home/azer/avaxia-monitpring-app/core-service/services/task/autoStartTaskCron.js:2:1041)
    at Object.exports.validateTask (/home/azer/avaxia-monitpring-app/core-service/controllers/task.controller.js:11:699)
    at async Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/task/updateState/validateTask.controller.test.js:219:5)
[2022-01-10T15:37:31.247] [ERROR] ma-core - Failed to validate the Task :failed to update the task NaN post 1234
[2022-01-10T15:37:31.253] [INFO] ma-core - update Task success testing testing testing
[2022-01-10T15:37:31.257] [INFO] ma-core - update Task success NaN post 1234
[2022-01-10T15:37:31.261] [ERROR] ma-core - update Task :You are not authorized to perform this action testing testing testing
[2022-01-10T15:37:31.264] [ERROR] ma-core - update Task :task not found NaN post 1234
[2022-01-10T15:37:31.337] [ERROR] ma-core - random Error
[2022-01-10T15:37:32.024] [ERROR] ma-core - random error
